### ISSUE TITLE
Android test and https

### ISSUE THREAD

**Issue by dejalatele** [wiremock/wiremock#112]
Hi 

I'm running Wiremock in an Android test application, but the test application crashes when the Wiremock server starts.  This is how I'm starting the Wiremock server

```
WireMockConfiguration config = wireMockConfig().port(8080).httpsPort(8443);
config.keystorePath(path_to_the_Keystore);
wireMockServer = new WireMockServer(config);
wireMockServer.start();
```

And here is fragment of the log error

```
 exception in execution.
 Caused by: java.lang.RuntimeException: java.io.IOException: !JsseListener: java.security.KeyStoreException: java.security.NoSuchAlgorithmException: KeyStore JKS implementation not found
    at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:186)
    ... 2 more
 Caused by: java.io.IOException: !JsseListener: java.security.KeyStoreException: java.security.NoSuchAlgorithmException: KeyStore JKS implementation not found
    at wiremock.org.mortbay.jetty.security.SslSocketConnector.newServerSocket(SslSocketConnector.java:516)
    at wiremock.org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:73)
    at wiremock.org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:283)
    at wiremock.org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:147)
    at wiremock.org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at wiremock.org.mortbay.jetty.Server.doStart(Server.java:235)
    at wiremock.org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:184)
```

The problem is related with the https initialization because if I remove the https  everything is ok.

How can I solve this issue?

Thanks

**Comment by LMojica** [comment]
I am getting the same error as dejalatele when I try to use https. This is how I am setting up my server on Android.

`mWireMockConfiguration.dynamicPort()
                .dynamicHttpsPort();
mWireMockServer = new WireMockServer(mWireMockConfiguration);
        mWireMockServer.start();`

It fails when I call .start() with the same error as dejalateles.

**Comment by tomakehurst** [comment]
Please could you re-post this on the mailing list? I don't have any experience configuring HTTPS on Android, so I won't be able to help. There are one or two Android devs on there who might.

**Comment by abhagupta** [comment]
Is there any solution found to this problem? I am running into the same issue.

**Comment by mikelupo** [comment]
Hi, any updates for this on android?

**Comment by abhagupta** [comment]
@mikelupo  Yes, this was merged long time ago in wiremock :-) https://github.com/tomakehurst/wiremock/pull/436   you can also view my bog if you need. https://medium.com/@abhaguptatweet/android-testing-with-mocking-fcec5b9f71c2#.dg4hvc31t

**Comment by mikelupo** [comment]
Thank you for the link.
