### ISSUE TITLE
Address Bind Issue

### ISSUE THREAD

**Issue by tejavadali** [wiremock/wiremock#141]
Hi, i have a serious problem with WireMock, i was giving all possible tries since 3 days, still no luck.

Issue : We have an project where in we pull data from various data sources (through REST API's), all went fine here, but while writing integration tests, we have 2 classes It1Test.java it2Test.java where in we use WireMock to stub API calls, each of these JUNIT test classes work when the other is commented but not otherwise. Can you tell me what am i missing here ??

Config:

JUNIT : 4.10
WireMock: 1.46
Here is the sample code template we are following.

class it1Test{
@Rule
public WireMockRule wireMockRule = new WireMockRule(8080);

@Before
public void stubRemoteCalls() {
// Stubbing calls
}

// Tests
}

class it2Test{
@Rule
public WireMockRule wireMockRule = new WireMockRule(8080);

@Before
public void stubRemoteCalls() {
// Stubbing calls
}

// Tests
}

Error :
java.lang.RuntimeException: java.net.BindException: Address already in use
7 at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:188)
8 at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:70)
9 at org.junit.rules.RunRules.evaluate(RunRules.java:20)
10 at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
11 at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:232)
12 at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
13 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
14 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
15 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
16 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
17 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
18 at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
19 at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
20 at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
21 at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:175)
22 at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
23 at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
24 at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
25 at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
26 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
27 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
28 Caused by: java.net.BindException: Address already in use
29 at java.net.PlainSocketImpl.socketBind(Native Method)
30 at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)
31 at java.net.ServerSocket.bind(ServerSocket.java:376)
32 at java.net.ServerSocket.(ServerSocket.java:237)
33 at wiremock.org.mortbay.jetty.bio.SocketConnector.newServerSocket(SocketConnector.java:80)
34 at wiremock.org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:73)
35 at wiremock.org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:283)
36 at wiremock.org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:147)
37 at wiremock.org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
38 at wiremock.org.mortbay.jetty.Server.doStart(Server.java:235)
39 at wiremock.org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
40 at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:186)
41 at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:70)
42 at org.junit.rules.RunRules.evaluate(RunRules.java:20)
43 at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
44 at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:232)
45 at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
46 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
47 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
48 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
49 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
50 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
"~/workspace/importer/api-importer/target/surefire-

Thanks in advance.

**Comment by KOTLAPRA23** [comment]
Hi Could you please help me here .

I am running wiremock junit test case and getting below exception every time
2020-04-10 20:51:34.541 INFO 84435 --- [ Test worker] o.s.b.a.e.web.EndpointLinksResolver : Exposing 2 endpoint(s) beneath base path ''
2020-04-10 20:51:34.822 INFO 84435 --- [ Test worker] org.eclipse.jetty.server.Server : jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 1.8.0_221-b11
2020-04-10 20:51:34.853 INFO 84435 --- [ Test worker] o.e.jetty.server.handler.ContextHandler : Started o.e.j.s.ServletContextHandler@a51c931{/__admin,null,AVAILABLE}
2020-04-10 20:51:34.856 INFO 84435 --- [ Test worker] o.e.jetty.server.handler.ContextHandler : Started o.e.j.s.ServletContextHandler@3d622400{/,null,AVAILABLE}
2020-04-10 20:51:34.869 INFO 84435 --- [ Test worker] o.e.jetty.server.AbstractConnector : Started NetworkTrafficServerConnector@709ceff2{HTTP/1.1,[http/1.1]}{0.0.0.0:5000}
2020-04-10 20:51:34.869 INFO 84435 --- [ Test worker] org.eclipse.jetty.server.Server : Started @80828ms

2020-04-10 20:53:40.153 INFO 84435 --- [tp780160597-117] o.e.j.s.handler.ContextHandler.ROOT : RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
2020-04-10 20:53:40.301 ERROR 84435 --- [qtp780160597-92] WireMock : Request was not matched as there were no stubs registered:
{
"url" : "/o/.well-known/openid-configuration",
"absoluteUrl" : "http://0.0.0.0:5000/o/.well-known/openid-configuration",
"method" : "GET",
"clientIp" : "127.0.0.1",
"headers" : {
"Cache-Control" : "max-age=0",
"Accept" : "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3",
"Upgrade-Insecure-Requests" : "1",
"Connection" : "keep-alive",
"User-Agent" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
"Host" : "0.0.0.0:5000",
"Accept-Encoding" : "gzip, deflate",
"Accept-Language" : "en-GB,en-US;q=0.9,en;q=0.8"
},
"cookies" : { },
"browserProxyRequest" : false,
"loggedDate" : 1586548420194,
"bodyAsBase64" : "",
"body" : "",
"scheme" : "http",
"host" : "0.0.0.0",
"port" : 5000,
"loggedDateString" : "2020-04-10T19:53:40Z",
"queryParams" : { }
}

Caused by: java.io.IOException: Failed to bind to /0.0.0.0:5000
at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.server.Server.doStart(Server.java:385)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:174)
... 67 common frames omitted
Caused by: java.net.BindException: Address already in use
at sun.nio.ch.Net.bind0(Native Method)
at sun.nio.ch.Net.bind(Net.java:433)
at sun.nio.ch.Net.bind(Net.java:425)
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
... 74 common frames omitted

Code sample:

@RunWith(SpringRunner.class)
@SpringBootTest(classes = Application.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@DirtiesContext
public abstract class SpringBootIntegrationTest {

@LocalServerPort
protected int port;
}

@configuration
@AutoConfigureWireMock(port = 5000)
public abstract class AuthorizationEnabledIntegrationTest extends SpringBootIntegrationTest {

@ClassRule
public static WireMockRule someService = new WireMockRule(options().port(5000).withRootDirectory("src/integrationTest/resources/mappings"));
}

inside mappings folder :
{
"priority": 1,
"mappings": [
{
"request": {
"method": "GET",
"url": "/o/.well-known/openid-configuration"
},
"response": {
"status": 200,
"headers": {
"Content-Type": "application/json"
},
"jsonBody": {
"issuer": "http://0.0.0.0:5000/o",
"jwks_uri": "http://0.0.0.0:5000/jwks"
}
}
}
]
}
