### ISSUE TITLE
Junit Jupiter Nested classes

### ISSUE THREAD

**Issue by nstdio** [wiremock/wiremock#1596]
When using `@WireMockTest` with two or more nested classes WireMock server never become running after first nested test class is executed.

WireMock: `wiremock-jre8: 2.31.0`

Here is demo:

```java
import com.github.tomakehurst.wiremock.junit5.WireMockRuntimeInfo;
import com.github.tomakehurst.wiremock.junit5.WireMockTest;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

@WireMockTest
class WiremockNested {
    @Nested
    class A {
        @Test
        void a(WireMockRuntimeInfo info) {
            assertDoesNotThrow(info::getHttpBaseUrl);
        }
    }

    @Nested
    class B {
        @Test
        void b(WireMockRuntimeInfo info) {
            assertDoesNotThrow(info::getHttpBaseUrl);
        }
    }
}
```

Resulting in exception:
```
org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.IllegalStateException: Not listening on HTTP port. Either HTTP is not enabled or the WireMock server is stopped.

	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:76)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:59)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3195)
	at com.demo.WiremockNested$A.a(WiremockNested.java:16)
	<ommited>
Caused by: java.lang.IllegalStateException: Not listening on HTTP port. Either HTTP is not enabled or the WireMock server is stopped.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
	at com.github.tomakehurst.wiremock.WireMockServer.port(WireMockServer.java:187)
	at com.github.tomakehurst.wiremock.junit5.WireMockRuntimeInfo.getHttpPort(WireMockRuntimeInfo.java:32)
	at com.github.tomakehurst.wiremock.junit5.WireMockRuntimeInfo.getHttpBaseUrl(WireMockRuntimeInfo.java:48)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:72)
	... 80 more
```

**Comment by tory-kk** [comment]
Faced the same issue while migrating from `WireMockClassRule` from `jUnit4` for inherited test classes. 
Example below:

```
import com.github.tomakehurst.wiremock.junit5.WireMockExtension;
import org.apache.commons.io.IOUtils;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

import static com.github.tomakehurst.wiremock.client.WireMock.*;
import static com.github.tomakehurst.wiremock.core.WireMockConfiguration.options;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

public abstract class A {

    @RegisterExtension
    static final WireMockExtension extension = WireMockExtension.newInstance()
            .options(options().port(8080))
            .configureStaticDsl(true)
            .build();

//    @ClassRule
//    public static WireMockClassRule wireMockClassRule = new WireMockClassRule(8080);

    private CloseableHttpClient httpClient;

    @BeforeEach
    public void init() {
        httpClient = HttpClients.createDefault();
    }

    @AfterEach
    public void close() throws IOException {
        httpClient.close();
    }

    @Test
    public void parentTest() throws Exception {
        // given
        stubFor(get(urlEqualTo("/test"))
                .willReturn(aResponse()
                        .withStatus(200)
                        .withBody("hello")
                )
        );

        // when
        final HttpResponse response = executeRequest();

        // then
        assertThat(getContent(response), is("hello"));
    }

    protected String getContent(final HttpResponse response) throws IOException {
        return IOUtils.toString(response.getEntity().getContent(), StandardCharsets.UTF_8);
    }

    protected HttpResponse executeRequest() throws IOException {
        return httpClient.execute(new HttpGet("http://localhost:8080/test"));
    }
}

class B extends A {

    @Test
    public void childBTest() throws Exception {
        // given
        stubFor(get(urlEqualTo("/test"))
                .willReturn(aResponse()
                        .withStatus(200)
                        .withBody("hello")
                )
        );

        // when
        final HttpResponse response = executeRequest();

        // then
        assertThat(getContent(response), is("hello"));
    }
}

class C extends A {

    @Test
    public void childCTest() throws Exception {
        // given
        stubFor(get(urlEqualTo("/test"))
                .willReturn(aResponse()
                        .withStatus(200)
                        .withBody("hello")
                )
        );

        // when
        final HttpResponse response = executeRequest();

        // then
        assertThat(getContent(response), is("hello"));
    }
}
```
