### ISSUE TITLE
Response templating may not be calculating correct dates

### ISSUE THREAD

**Issue by jamietanna** [wiremock/wiremock#1608]
As seeing on #1592:

```
com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformerTest > canTruncateARenderableDate FAILED
    java.lang.AssertionError: 
    Expected: is "2021-10-01"
         but: was "2021-09-01"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformerTest.canTruncateARenderableDate(ResponseTemplateTransformerTest.java:1054)
```

It appears that we've either got a defect in the way that `'first day of month'` calculates, or the way the test works :thinking:

**Comment by tomakehurst** [comment]
Working on this right now
