### ISSUE TITLE
SocketException: Broken pipe when Maven run test

### ISSUE THREAD

**Issue by RNiveau** [wiremock/wiremock#165]
Hi,

I would like to use wireMock to do integration tests on my application which use somes web service.

I do a simple test like this to try wireMock:

``` java
public void test() {
WireMockServer wireMockServer = new WireMockServer(WireMockConfiguration.wireMockConfig().port(8180));
wireMockServer.start();
WireMock.stubFor(post(urlEqualTo("myurl"))
                    .willReturn(aResponse()
                            .withStatus(200)
                            .withHeader("Content-Type", "text/xml")
                            .withBody("<content>mycontent</content))));

// run test
}
```

When I run it in IntelliJ, all works fine.

But when I run:

``` bash
mvn clean install
```

I get this:

```
2014-08-14 16:49:02 INFO  DefaultHttpClient:728 - I/O exception (java.net.SocketException) caught when processing request: Broken pipe
2014-08-14 16:49:02 INFO  DefaultHttpClient:735 - Retrying request

java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
    at wiremock.org.apache.http.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:169)
    at wiremock.org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:119)
    at wiremock.org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:126)
    at wiremock.org.apache.http.entity.StringEntity.writeTo(StringEntity.java:176)
    at wiremock.org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:98)
    at wiremock.org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
    at wiremock.org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:122)
    at wiremock.org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:271)
    at wiremock.org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:197)
    at wiremock.org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:257)
    at wiremock.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
    at wiremock.org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:717)
    at wiremock.org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:522)
    at wiremock.org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
    at wiremock.org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at wiremock.org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
    at com.github.tomakehurst.wiremock.client.HttpAdminClient.postJsonAssertOkAndReturnBody(HttpAdminClient.java:149)
    at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:70)
    at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:118)
    at com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:61)
    at com.github.tomakehurst.wiremock.client.WireMock.stubFor(WireMock.java:65)
```

What's wrong in my test ?

Thanks.

**Comment by khong07** [comment]
Hi,

I'm facing now the same problem, because of the endpoint `wiremocked` is not yet available (asynchronously??) , so the http client will throw broken pipe ...

If I add some miliseconds between stubFor and my test, it will be ok...
