### ISSUE TITLE
Wiremock : when trying to connect https stub of wiremock getting excetion :: Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by Trupti-Vhare** [wiremock/wiremock#1659]
Https stub configuration : 

WireMockServer mockServer = new WireMockServer(WireMockConfiguration.wireMockConfig()
				.extensions(new ResponseTemplateTransformer(true), new AsyncExtension(),
						new AsyncExtensionPro())
				.port(Integer.valueOf(env.getProperty("wiremock.http.port").toString()))
				.httpsPort(Integer.valueOf(env.getProperty("wiremock.https.port").toString()))
				.keystorePath("./src/main/resources/keystore.jks").keystorePassword("password").keystoreType("JKS")
				.notifier(new ConsoleNotifier(true)));

		mockServer.start();

- wiremock stub working fine for HTTP but not for HTTPS( I have provided keystore certificate file path as well ) .
- full trace exception on server is : 
- Caused by: java.security.PrivilegedActionException: null
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_191]
        at com.sun.xml.messaging.saaj.client.p2p.HttpSOAPConnection.call(HttpSOAPConnection.java:140) ~[saaj-impl-1.3.jar:1.3]
        ... 105 common frames omitted
Caused by: com.sun.xml.messaging.saaj.SOAPExceptionImpl: Message send failed
        at com.sun.xml.messaging.saaj.client.p2p.HttpSOAPConnection.post(HttpSOAPConnection.java:344) ~[saaj-impl-1.3.jar:1.3]
        at com.sun.xml.messaging.saaj.client.p2p.HttpSOAPConnection$PriviledgedPost.run(HttpSOAPConnection.java:169) ~[saaj-impl-1.3.jar:1.3]
        ... 107 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_191]
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[na:1.8.0_191]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.8.0_191]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.8.0_191]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[na:1.8.0_191]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[na:1.8.0_191]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259) ~[na:1.8.0_191]

2) when I tried to check connectivity with wget command ---
result : 
Initiating SSL handshake.
SSL handshake failed.
OpenSSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Closed fd 3
Unable to establish SSL connection.

Can you help me with this ?.. I tried a lot of things.
Thanks in advance .

**Comment by maxifly** [comment]
Have a same problem. But use Wiremock as TestExtention

`    @RegisterExtension
    static WireMockExtension wm = newInstance()
            .options(wireMockConfig()
                    .httpsPort(8888)
                    .needClientAuth(true)
                    .keystorePath("src/test/resources/ssl/server-cacerts.jks")
                    .keystorePassword("q123456")
                    .keyManagerPassword("q1234567")`
                    
Prepare keystore use command
`keytool -import -keystore server-cacerts -file server.crt`
