### ISSUE TITLE
DateTimeParser does not parse only time.

### ISSUE THREAD

**Issue by nstdio** [wiremock/wiremock#1660]
Hi, guys. I would expect this test case to pass, but it didn't.
```java
    @Test
    public void parsesOnlyTime() {
        // given
        DateTimeParser parser = DateTimeParser.forFormat("HH:mm:ss");
        LocalDateTime expected = LocalDate.now().atTime(LocalTime.parse("11:12:13"));

        // when
        RenderableDate actual = parser.parseDate("11:12:13");

        // then
        assertThat(actual, is(expected));
    }
```

Instead I got an exception:

```
Unable to obtain LocalDateTime from TemporalAccessor: {},ISO resolved to 11:12:13 of type java.time.format.Parsed
java.time.DateTimeException: Unable to obtain LocalDateTime from TemporalAccessor: {},ISO resolved to 11:12:13 of type java.time.format.Parsed
	at java.base/java.time.LocalDateTime.from(LocalDateTime.java:461)
	at com.github.tomakehurst.wiremock.common.DateTimeParser.parseDate(DateTimeParser.java:138)
	at com.github.tomakehurst.wiremock.common.DateTimeParserTest.parsesOnlyTime(DateTimeParserTest.java:109) <63 internal lines>
Caused by: java.time.DateTimeException: Unable to obtain LocalDate from TemporalAccessor: {},ISO resolved to 11:12:13 of type java.time.format.Parsed
	at java.base/java.time.LocalDate.from(LocalDate.java:396)
	at java.base/java.time.LocalDateTime.from(LocalDateTime.java:456)
	... 65 more
```

This is caused by querying for only time part and parsing full datetime afterwards.

**Comment by arthur-star** [comment]
I found a relevant issue for this problem https://github.com/wiremock/wiremock/issues/1643, this may be caused by the fix of it.

**Comment by tomakehurst** [comment]
I'm not convinced the date helpers should work with time only, since under the hood you're still working with a date object.

I get that (like the above example) you can default to today's date, but I suspect there will be some unintended consequences to that.

A dedicated `time` helper might be a better option.
