### ISSUE TITLE
Support MITM proxying on JDK 17

### ISSUE THREAD

**Issue by tomakehurst** [wiremock/wiremock#1706]
The HTTPS forward proxy feature makes use of some Sun classes in order to generate X509 certificates. These classes are no longer available in JDK 17 and beyond so a long term solution is needed to restore this capability.

**Comment by rodrigorodrigues** [comment]
Hi @tomakehurst,

Trying to run a Spring Boot App with JDK 17 and go this issue, is this the same? I can try to help.

	Caused by: java.lang.IllegalStateException: No Server ALPNProcessors!

	Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt in java.library.path: /Users/rodrigo/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
		at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
		at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
		at java.base/java.lang.System.loadLibrary(System.java:1989)
		at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
		at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
		at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
		... 90 more
