### ISSUE TITLE
InvalidPathException if Wiremock recording URL contains a colon

### ISSUE THREAD

**Issue by maknesium** [wiremock/wiremock#1768]
Hi,

first of all, I am using the latest version of wiremock 2.32.0.

I've been using wiremock to record and snapshot a URL which contains a colon like: https://myserver.com/data/API/Checks(AccountID='123456789',Number='987654321',CompanyCode='9999',ReadingDate=datetime'2022-01-12T00:00:00')

The request/response can be recorded and snapshotted by wiremock, successfully. Now, when I start wiremock and let it load the mapping by issuing the aforementioned request against the wiremock instance, I'll get an eception (see Exception stack trace below) which indicates, that the colon cannot be path of the filename.

As indicated in issue 461 (https://github.com/wiremock/wiremock/issues/461) colons have to be stripped out when writing the file containing request url and response data.

It seems like this has to be done, when reading back the file as well. Am I missing a filter?

Exception stack trace:

`2022-01-12 19:09:59,493 WARN [org.ecl.jet.ser.ResourceService] (qtp87553727-125) EXCEPTION : java.nio.file.InvalidPathException: Illegal char <:> at index 152: C:\dev\backend\src\test\resources\/__files/data/API/Checks(AccountID='123456789',Number='987654321',CompanyCode='9999',ReadingDate=datetime'2022-01-12T00:00:00') at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229) at org.eclipse.jetty.util.resource.PathResource.<init>(PathResource.java:266) at org.eclipse.jetty.util.resource.PathResource.addPath(PathResource.java:380) at org.eclipse.jetty.servlet.DefaultServlet.getResource(DefaultServlet.java:416) at org.eclipse.jetty.server.CachedContentFactory.getContent(CachedContentFactory.java:188) at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:241) at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:447) at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631) at com.github.tomakehurst.wiremock.servlet.TrailingSlashFilter.doFilter(TrailingSlashFilter.java:41) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at com.github.tomakehurst.wiremock.servlet.ContentTypeSettingFilter.doFilter(ContentTypeSettingFilter.java:45) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:229) at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:81) at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.forwardToFilesContext(WireMockHandlerDispatchingServlet.java:320) at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.access$300(WireMockHandlerDispatchingServlet.java:46) at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet$ServletHttpResponder.respondTo(WireMockHandlerDispatchingServlet.java:212) at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet$ServletHttpResponder.respondSync(WireMockHandlerDispatchingServlet.java:173) at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet$ServletHttpResponder.respond(WireMockHandlerDispatchingServlet.java:167) at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:97) at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:142) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763) at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.Server.handle(Server.java:516) at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400) at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by bjornarl** [comment]
I've been experiencing this issue on Windows since version 2.28.0 (version 2.24.0 didn't trigger it).
For me, it seems to only occur if there is no matching mocked request at test execution time. If there is a manually mocked request that matches or a previously recorded request that matches, I don't get the error.
Also it does not seem to help to use `%3A` instead of `:` in the request URL as either way the stack trace has the filename with the colon.

**Comment by desmond27** [comment]
I just faced this same issue, but with the pipe `|` character.

In my case, the URI is generated by a third party SDK library (Auth0 management API) as follows: `/api/v2/users/auth0|123456789/roles`.

The pipe here is triggering this exception.

**Comment by tomakehurst** [comment]
@desmond27 the OP's stack trace implies that the problem was triggered by a request not being matched. WireMock will attempt to find a file matching the path if all else fails, so if the URL path contains characters that the underlying OS doesn't like then it'll fail.

This is avoidable by ensuring your request will be matched by a stub mapping.

**Comment by desmond27** [comment]
>if the URL path contains characters that the underlying OS doesn't like then it'll fail

I mean this is what I need a workaround for since a pipe character is valid in URIs and therefore must be supported IMO regardless of the underlying OS. Perhaps the URI could be URL encoded before matching if required by implementing a flag? 

Matching via a stub might work for some test cases, but might not for more specific test cases.

**Comment by tomakehurst** [comment]
A stub like this will work just fine:

```json
{
  "request": {
    "method": "GET",
    "urlPath": "/api/v2/users/auth0|123456789/roles"
  },
  
  "response": {
    "status": 200,
    "body": "{ \"message\": \"Put your response body here\" }"
  }
}
```

**Comment by maknesium** [comment]
I have the files of several stubs inside a directory and have to rely on wiremock to find the correct one. This works quite well. All we need is a rule that maps non-supported file system characters like "-" or "|" to a simple "_" and we can just put in the correct file for wiremock to load.

**Comment by tomakehurst** [comment]
The stub filename doesn't have to be the same as the URL or any part of it.

You can have a bunch of files called one.json, two.json etc. if you want, or one big file called something like stubs.json with all of them in.

The URL matching file system path is only relevant when no stub matched and WireMock is attempting to find a match where URL path = file system path. It's not a good idea to rely on this except for when you've got a whole load of static assets that have straightforward filenames.

**Comment by desmond27** [comment]
I see. Actually I misunderstood the error. I am still getting a hang of WireMock.

I had actually not stubbed the roles API I mentioned above and I incorrectly assumed that WireMock always looks in the file system. I have since changed the stub to use `urlPattern()`  instead of an absolute URL and now I have bypassed the issue.

**Comment by maknesium** [comment]
> The stub filename doesn't have to be the same as the URL or any part of it.
> 
> You can have a bunch of files called one.json, two.json etc. if you want, or one big file called something like stubs.json with all of them in.
> 
> The URL matching file system path is only relevant when no stub matched and WireMock is attempting to find a match where URL path = file system path. It's not a good idea to rely on this except for when you've got a whole load of static assets that have straightforward filenames.

Okay, I used the "record" functionality to save lots a requests against a backend system with the proxy mode of wiremock to their respecitive files. My tests then boot up a wiremock instance pointing to that directory with the recorded files emulating the original backend system. That's when I hit the problem that some characters cannot be mapped to the file system. That's my use case.

Can I set an option so that wiremock records all proxied requests into a single file and load those stubs from that file?

**Comment by tomakehurst** [comment]
@maknesium were you using the current or legacy recorder?

**Comment by maknesium** [comment]
I am setting up the recording with `java -jar wiremock-jre8-standalone-2.32.0.jar --port 8000 --verbose --proxy-all="http://acme.host.com:8000" --record-mappings --preserve-host-header --print-all-network-traffic --disable-gzip` and I write the mappings to the file system by calling `curl -o nul -X POST http://localhost:8000/__admin/recordings/snapshot`

**Comment by mkp05** [comment]
Any news on this?
I'm facing similar problem as originally described, but during simple tests run on Windows.

> I would always recommend using stubs explicitly rather than relying on the default file serving approach, except for things like images/other static asserts.
> 
> It's always possible to use a stub, and they'll accept characters like `|` in the URL path spec.

Of course, but it's not always possible - when you inherit tons of code which ignored this suggestion you cannot fix all of it at once and still have to work on it.

Looking for some solution I have found in library code trigger named `shouldForwardToFilesContext` which should probably solve/hide the problem it but I can't make it work. It would be nice to have it either available via wiremock configuration builder or (even better) via property described in documentation.
