### ISSUE TITLE
Invalid XML Declaration in a request body causes wiremock to respond with code 500

### ISSUE THREAD

**Issue by rickpock** [wiremock/wiremock#1838]
## Bug reports

We're a lot more likely to look at and fix bugs that are clearly described and reproduceable. Please including the following details when reporting a bug:

- Wiremock versions: 2.18.0 and 2.32.0
- Wiremock started with: `java -jar ~/Downloads/wiremock-jre8-standalone-2.32.0.jar --verbose --container-threads 200 --https-port 8080 --port 0 --root-dir "wiremock-test" --proxy-all="https://__HOST__/" --record-mappings --match-headers="Accept,Content-Type,Cache-Control"` where `__HOST__` is the FQDN for a Cisco UCS Manager.
- Test case: Run the following curl command, where `__USERNAME__` and `__PASSWORD__` are a username and password, respectively, for the target Cisco UCS Manager:
```curl --request POST   --url https://localhost:8080/nuova   --header 'Content-Type: application/xml'   --data '<?xml version="1.0" encoding="UTF-8"?><?xml version="1.0"?><aaaLogin inPassword="__PASSWORD__" inName="__USERNAME__"/>' -k```

Expected behavior:
The response should be the same as if the curl was against the underlying host (`__HOST__`). Example, with the outCookie censored:
``` <aaaLogin cookie="" response="yes" outCookie="__COOKIE__" outRefreshPeriod="600" outPriv="read-only" outDomains="" outChannel="noencssl" outEvtChannel="noencssl" outSessionId="web_15047_A" outVersion="4.0(1b)" outName="rodev"> </aaaLogin>```

Actual behavior:
500 HTTP Status Code from the wiremock server.
```<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 java.lang.IllegalArgumentException: URI path begins with multiple slashes</title>
</head>
<body><h2>HTTP ERROR 500 java.lang.IllegalArgumentException: URI path begins with multiple slashes</h2>
<table>
<tr><th>URI:</th><td>/nuova</td></tr>
<tr><th>STATUS:</th><td>500</td></tr>
<tr><th>MESSAGE:</th><td>java.lang.IllegalArgumentException: URI path begins with multiple slashes</td></tr>
<tr><th>SERVLET:</th><td>com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-6b26e945</td></tr>
<tr><th>CAUSED BY:</th><td>java.lang.IllegalArgumentException: URI path begins with multiple slashes</td></tr>
</table>
<h3>Caused by:</h3><pre>java.lang.IllegalArgumentException: URI path begins with multiple slashes
	at wiremock.org.apache.hc.core5.util.Args.check(Args.java:41)
	at wiremock.org.apache.hc.core5.http.message.BasicHttpRequest.setUri(BasicHttpRequest.java:281)
	at wiremock.org.apache.hc.core5.http.message.BasicHttpRequest.&lt;init&gt;(BasicHttpRequest.java:123)
	at wiremock.org.apache.hc.core5.http.message.BasicClassicHttpRequest.&lt;init&gt;(BasicClassicHttpRequest.java:91)
	at wiremock.org.apache.hc.client5.http.classic.methods.HttpUriRequestBase.&lt;init&gt;(HttpUriRequestBase.java:45)
	at wiremock.org.apache.hc.client5.http.classic.methods.HttpPost.&lt;init&gt;(HttpPost.java:50)
	at wiremock.org.apache.hc.client5.http.classic.methods.HttpPost.&lt;init&gt;(HttpPost.java:60)
	at com.github.tomakehurst.wiremock.http.HttpClientFactory.getHttpRequestFor(HttpClientFactory.java:248)
	at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.getHttpRequestFor(ProxyResponseRenderer.java:173)
	at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.render(ProxyResponseRenderer.java:101)
	at com.github.tomakehurst.wiremock.http.StubResponseRenderer.buildResponse(StubResponseRenderer.java:64)
	at com.github.tomakehurst.wiremock.http.StubResponseRenderer.render(StubResponseRenderer.java:54)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:74)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:142)
	at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:516)
	at wiremock.org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at wiremock.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at wiremock.org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:352)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
	at wiremock.org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:183)
	at wiremock.org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:138)
	at wiremock.org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:361)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at wiremock.org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at wiremock.org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at wiremock.org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at wiremock.org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at wiremock.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)
</pre>

</body>
</html>```


It appears that wiremock is parsing the xml request body, and erroring, even though the server being mocked is able to handle the request fine.

I am not disputing that the request body is malformed xml, but it's not up to wiremock to decide that. I expect wiremock to respond the same way as the server it is mocking.

**Comment by rickpock** [comment]
Okay, that error message doesn't make any sense. I tried to isolate the test for a more clear bug report, but this is exhibiting a different problem. Sorry for the confusion. I'll track it down and correct the bug report.

**Comment by rickpock** [comment]
The report has been updated, and now the error message makes sense for what I'm trying to report.
