### ISSUE TITLE
500 Response using Content-Type header text/xml;charset=utf-16

### ISSUE THREAD

**Issue by purepvd** [wiremock/wiremock#1926]
When sending a POST request with `Content-Type` header of `text/xml;charset=utf-16` to a mapping, an error is returned from wiremock:

`com.github.tomakehurst.wiremock.common.xml.XmlException: { "errors" : [ { "code" : 50, "title" : "Content is not allowed in prolog.", "detail" : "Content is not allowed in prolog.; line 1; column 1" } ] }`

**Mapping**

        {
            "id": "05725fdd-e9fb-47c7-a462-cf67de28a0f1",
            "request": {
                "url": "/HttpStatusCodeEcho/200",
                "method": "ANY"
            },
            "response": {
                "status": 200,
                "body": "Wiremock Body 200",
                "headers": {
                    "Content-Type": "text/plain"
                }
            },
            "uuid": "05725fdd-e9fb-47c7-a462-cf67de28a0f1",
            "persistent": true
        },

**Request Body**

```
<?xml version="1.0" encoding="utf-16"?>
<helloWorld>Hello</helloWorld>
```

In my testing it did not matter whether the declaration `<?xml version="1.0" encoding="utf-16"?>` was included or not.

**Full Wiremock Response**

```
<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 com.github.tomakehurst.wiremock.common.xml.XmlException: { "errors" : [ { "code" : 50, "title" : "Content is not allowed in prolog.", "detail" : "Content is not allowed in prolog.; line 1; column 1" } ] }</h2>

URI: | /HttpStatusCodeEcho/200
-- | --
500
com.github.tomakehurst.wiremock.common.xml.XmlException: { "errors" : [ { "code" : 50, "title" : "Content is not allowed in prolog.", "detail" : "Content is not allowed in prolog.; line 1; column 1" } ] }
com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-26d10f2e
com.github.tomakehurst.wiremock.common.xml.XmlException: { "errors" : [ { "code" : 50, "title" : "Content is not allowed in prolog.", "detail" : "Content is not allowed in prolog.; line 1; column 1" } ] }

<h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">com.github.tomakehurst.wiremock.common.xml.XmlException: {
  "errors" : [ {
    "code" : 50,
    "title" : "Content is not allowed in prolog.",
    "detail" : "Content is not allowed in prolog.; line 1; column 1"
  } ]
}
	at com.github.tomakehurst.wiremock.common.xml.XmlException.fromSaxException(XmlException.java:40)
	at com.github.tomakehurst.wiremock.common.xml.Xml.read(Xml.java:125)
	at com.github.tomakehurst.wiremock.matching.EqualToXmlPattern.&lt;init&gt;(EqualToXmlPattern.java:75)
	at com.github.tomakehurst.wiremock.matching.EqualToXmlPattern.&lt;init&gt;(EqualToXmlPattern.java:64)
	at com.github.tomakehurst.wiremock.client.WireMock.equalToXml(WireMock.java:225)
	at com.github.tomakehurst.wiremock.stubbing.StubMappingJsonRecorder.valuePatternForContentType(StubMappingJsonRecorder.java:135)
	at com.github.tomakehurst.wiremock.stubbing.StubMappingJsonRecorder.buildRequestPatternFrom(StubMappingJsonRecorder.java:91)
	at com.github.tomakehurst.wiremock.stubbing.StubMappingJsonRecorder.requestReceived(StubMappingJsonRecorder.java:58)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:90)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:142)
	at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:516)
	at wiremock.org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at wiremock.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at wiremock.org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at wiremock.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)</pre>
```

**Wiremock Docker Output**
```
2022-07-18 15:18:03.127 Request received:
nnn.nn.nn.nnn - POST /HttpStatusCodeEcho/200

Accept: [*/*]
User-Agent: [PostmanRuntime/7.29.0]
Connection: [keep-alive]
Postman-Token: removed
Host: removed
Accept-Encoding: [gzip, deflate, br]
Content-Length: [71]
Content-Type: [text/xml;charset=utf-16]
㰿硭氠癥牳楯渽∱⸰∠敮捯摩湧㴢畴昭ㄶ∿㸍਼桥汬潗潲汤㹈敬汯㰯桥汬潗潲汤�


Matched response definition:
{
  "status" : 200,
  "body" : "Wiremock Body 200",
  "headers" : {
    "Content-Type" : "text/plain"
  }
}

Response:
HTTP/1.1 200
Content-Type: [text/plain]
Matched-Stub-Id: [05725fdd-e9fb-47c7-a462-cf67de28a0f1]
```

**Wiremock Info**
v2.32.0 (official docker image)

**Comment by tomakehurst** [comment]
The exception you're seeing is due to another stub (not the one you've pasted here) that uses the `equalToXml` matcher and has a malformed expected value. If you fix this, then the request you're making should start to work.

**Comment by purepvd** [comment]
> The exception you're seeing is due to another stub (not the one you've pasted here) that uses the `equalToXml` matcher and has a malformed expected value. If you fix this, then the request you're making should start to work.

Thanks for having a look. Doesn't the `Matched-Stub-Id: [05725fdd-e9fb-47c7-a462-cf67de28a0f1]` of the docker output indicate it matched my request to what I expect?

I took a look at my other mappings and none use `equalToXml` as a matcher.

**Comment by purepvd** [comment]
I haven't been able to get it working from postman still, but my application code uses little endian byte order so I tried sending a content type header of `text/xml;charset=utf-16le` and it actually worked this way from the application code. It makes no difference from postman though. There might be byte order marks involved from the application code but I haven't been able to find them or rule that out. I tried testing with and without BOMs but nothing made a difference. I'm not confident I was actually getting the application code to output BOMs during my testing.

**Comment by tomakehurst** [comment]
From this line: `at com.github.tomakehurst.wiremock.stubbing.StubMappingJsonRecorder.valuePatternForContentType(StubMappingJsonRecorder.java:135)` it seems you've got the legacy recorder running when you see this issue. This isn't supported any more and is still present only for backwards compatibility.

If recording is what you're attempting, I suggest trying to new recorder instead.

**Comment by purepvd** [comment]
> From this line: `at com.github.tomakehurst.wiremock.stubbing.StubMappingJsonRecorder.valuePatternForContentType(StubMappingJsonRecorder.java:135)` it seems you've got the legacy recorder running when you see this issue. This isn't supported any more and is still present only for backwards compatibility.
> 
> If recording is what you're attempting, I suggest trying to new recorder instead.

Ahh yes you're correct. It looks like the legacy recorder is in use. I can try switching it over to see if that helps.

**Comment by tomakehurst** [comment]
Closing, since there seems to be a way forward.
