### ISSUE TITLE
bodyFileName does not parse soapXPath request.body

### ISSUE THREAD

**Issue by NickOppersdorff-Velo** [wiremock/wiremock#1952]
## Bug reports

I have the following soapXPath which I am able to use with no problem within an XML response template e.g. _response.xml_
`{{soapXPath request.body '/FindABank/xmlDocRequest/FindABankArgs/RequestDetails/Country/text()'}}`

I can use it as follows:
`<ns2:CountryCode>{{soapXPath request.body '/FindABank/xmlDocRequest/FindABankArgs/RequestDetails/Country/text()'}}</ns2:CountryCode>`

In the response I can see `<ns2:CountryCode>GB</ns2:CountryCode>`

The issue I am having is that the same soapXPath does not seem to work if I use it to reference a bodyFileName:

`"response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/soap+xml"
        },
        "transformers": ["response-template"],
        "bodyFileName": "responses/{{soapXPath request.body '/FindABank/xmlDocRequest/FindABankArgs/RequestDetails/Country/text()'}}.xml"
    }`

In this case I get a 500 response and the following error
`java.io.FileNotFoundException: /data/__files/responses/{{xPath request.body &apos;/soap:Envelope/soap:Body/f:FindABank/f:xmlDocRequest/p:FindABankArgs/p:RequestDetails/p:Country/text()&apos;}}.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:138)
	at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)`

My startup command is _java -XX:+UseG1GC -XX:MaxGCPauseMillis=30 -Xms6m -Xmx64m -jar /wiremock-jre8-standalone-2.33.2.jar --port 80 --root-dir /data --no-request-journal --local-response-templating_

I have noticed this on both wiremock 2.18.0 and 2.33.2.

Any help appreciated

**Comment by tomakehurst** [comment]
Can you post the actual SOAP request this is failing with?

**Comment by NickOppersdorff-Velo** [comment]
```
<?xml version='1.0' encoding='UTF-8'?>
<S:Envelope xmlns:S="http://www.w3.org/2003/05/soap-envelope">
    <S:Header>
        <AuthenticationHeader xmlns="http://com.testcorp/TestAPIWebService">
            <Username>xxxxxxxxxx</Username>
            <Password>xxxxxxxxxx</Password>
            <ProcessorId>123</ProcessorId>
        </AuthenticationHeader>
        <To xmlns="http://www.w3.org/2005/08/addressing">http://localhost:11696/1234</To>
        <Action xmlns="http://www.w3.org/2005/08/addressing" xmlns:S="http://www.w3.org/2003/05/soap-envelope" S:mustUnderstand="true">http://com.testcorp/TestAPIWebService/TestAPIWebService/BankSearch</Action>
        <ReplyTo xmlns="http://www.w3.org/2005/08/addressing">
            <Address>http://www.w3.org/2005/08/addressing/anonymous</Address>
        </ReplyTo>
        <FaultTo xmlns="http://www.w3.org/2005/08/addressing">
            <Address>http://www.w3.org/2005/08/addressing/anonymous</Address>
        </FaultTo>
        <MessageID xmlns="http://www.w3.org/2005/08/addressing">uuid:50728337-e753-4077-9422-409beb7729d3</MessageID>
    </S:Header>
    <S:Body>
        <FindABank xmlns="http://com.testcorp/TestAPIWebService" xmlns:ns2="rrn:com.testcorp:schemas/TestAPI/v1_0/TestAPIWebServiceParams.xsd" xmlns:ns3="rrn:com.ruesch:schemas/nexus/v1_0/core.xsd" xmlns:ns4="http://com.testcorp/TestAPIWebService">
            <xmlDocRequest>
                <ns2:FindABankArgs>
                    <ns2:RequestDetails>
                        <ns2:Country>GB</ns2:Country>
                        <ns2:IBANNumber>xxxxxxxxxxxxxxx</ns2:IBANNumber>
                        <!-- <ns2:RoutingCode>xxxxxxxxxxxxxxx</ns2:RoutingCode> -->
                    </ns2:RequestDetails>
                </ns2:FindABankArgs>
            </xmlDocRequest>
        </FindABank>
    </S:Body>
</S:Envelope>
```

**Comment by tomakehurst** [comment]
I can't replicate this issue. The below stub JSON, a file called `GB.xml` + your request returned the expected result:

```json
{
    "request": {
      "method": "POST",
      "urlPath": "/soap"
    },
    "response": {
      "status": 200,
      "transformers": [
        "response-template"
      ],
      "bodyFileName": "responses/{{soapXPath request.body '/FindABank/xmlDocRequest/FindABankArgs/RequestDetails/Country/text()'}}.xml"
    }
  }
```

**Comment by NickOppersdorff-Velo** [comment]
@tomakehurst, sorry for the slow response, I completely missed this.  Let me try with your JSON stub and I will close this ticket if it works.
