### ISSUE TITLE
 [trust-all-proxy-targets] are unavailable given other options on the command line

### ISSUE THREAD

**Issue by NewbieProger** [wiremock/wiremock#1958]
When I put '--trust-all-proxy-targets' i've got this exc:
```
Exception in thread "main" joptsimple.UnavailableOptionException: Option(s) [trust-all-proxy-targets] are unavailable given other options on the command line
        at joptsimple.OptionParser.ensureAllowedOptions(OptionParser.java:434)
        at joptsimple.OptionParser.parse(OptionParser.java:401)
        at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.<init>(CommandLineOptions.java:342)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:56)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:140)
```

**Comment by tomakehurst** [comment]
Please post questions to the mailing list
