### ISSUE TITLE
Problems wth CONNECT requests

### ISSUE THREAD

**Issue by lzolkiewski** [wiremock/wiremock#1970]
## The problem 
Hi while trying to change WireMock to work with traffic in integration tests without the need to override base urls I've encountered a following problem. In one of services we are using reactor netty http client and this lead to an exception that was not observed on other services. I've learned that this one client despite `http` protocol uses `CONNECT` requests while creating tunnel https://github.com/netty/netty/issues/10475. It was causing similar issues to the ones I've had on other services while trying to use `https` requests through WireMock (server was configured based on documentation to accept https requests). This lead me to wonder that WireMock might not be handling `CONNECT` requests, or something around it, well. 

## Setup 
- version - com.github.tomakehurst:wiremock-jre8:2.34.0
- example - https://github.com/lzolkiewski/wiremock-connect-problem

## Feature requests
I'd like to be able to use netty's httpClient with WireMock when it works as a proxy.
Also I'd like WireMock to handle well requests that require CONNECT request.

## Details
Before update to the latest version I was prompted to match CONNECT requests by hand, since though following exception is being thrown while using netty HttpClient:
```java
org.opentest4j.AssertionFailedError: expected: <null> but was: <reactor.core.Exceptions$ReactiveException: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response>
	at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at app//org.junit.jupiter.api.AssertNull.failNotNull(AssertNull.java:50)
	at app//org.junit.jupiter.api.AssertNull.assertNull(AssertNull.java:35)
	at app//org.junit.jupiter.api.AssertNull.assertNull(AssertNull.java:30)
```
Through Wireshark following can be seen:
![image](https://user-images.githubusercontent.com/62542051/191986785-ccd7df32-3e3b-450e-a2e7-64028c702d3f.png)
![image](https://user-images.githubusercontent.com/62542051/191987001-d3c24c27-f446-4133-81fb-375a7d84a33e.png)
![image](https://user-images.githubusercontent.com/62542051/191987113-b5fd7117-26b0-472a-9c2f-cbe10ecd8b7e.png)
![image](https://user-images.githubusercontent.com/62542051/191987399-77cad858-888a-4d3f-8ab4-51fa3d6e86a4.png)
![image](https://user-images.githubusercontent.com/62542051/191987491-3e30b58c-e17d-45ce-9ef7-f8bc57182a0e.png)
![image](https://user-images.githubusercontent.com/62542051/191987751-c1944a61-722e-4081-b1bf-fa0689bbba28.png)
![image](https://user-images.githubusercontent.com/62542051/191987880-a6714691-d91f-4c41-95b0-c58259a99f67.png)

Thank you for any guidance

**Comment by tomakehurst** [comment]
I've raised this PR against your demo app showing how to fix most of this: https://github.com/lzolkiewski/wiremock-connect-problem/pull/1

There's still potentially an issue with the client using CONNECT for unencrypted connections, which WireMock doesn't currently support.

**Comment by lzolkiewski** [comment]
Thank you so much for your help :) 
Would you like for me to leave this issue open for the issue with the client using CONNECT for unencrypted connections?

**Comment by maxime700** [comment]
Hi, 
I'm facing the same issue. 

@tomakehurst, any news for unencrypted connections? 

Sinceraly.

**Comment by tomakehurst** [comment]
No, we haven't spent any time on this as it's a very niche edge case.

**Comment by rajvinodh** [comment]
@tomakehurst 

Client (Android device) is calling below CONNECT, I need to add a header and let it forward. Direct it me if it is possible.

Opened Socket[addr=/127.0.0.1,port=55956,localport=8081]
Incoming bytes: CONNECT firebase-settings.crashlytics.com:443 HTTP/1.1

Opened Socket[addr=/127.0.0.1,port=55928,localport=8081]
Incoming bytes: CONNECT infinitedata-pa.googleapis.com:443 HTTP/1.1
