### ISSUE TITLE
Sending multipart requests to Wiremock fails with "Stream ended unexpectedly"

### ISSUE THREAD

**Issue by Spencerooni** [wiremock/wiremock#1973]
Issues occurs in Wiremock 3.32.0 and later (did not throw exception in 3.31).

Starting Wiremock in docker with definition:

```
image: wiremock/wiremock:2.32.0-alpine
command: --local-response-templating
```

Our application sends multipart requests to an external API (which we have used Wiremock to mock so we can test our API independently). However since updating to Wiremock 3.32, it fails when we send a multipart request. The body of the response:

```
<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 wiremock.javax.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: Stream ended unexpectedly</h2>

URI: | /test-url
-- | --
500
wiremock.javax.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: Stream ended unexpectedly
com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-3bcbb589
wiremock.javax.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: Stream ended unexpectedly
wiremock.org.apache.commons.fileupload.FileUploadException: Stream ended unexpectedly
wiremock.org.apache.commons.fileupload.MultipartStream$MalformedStreamException: Stream ended unexpectedly

<h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">wiremock.javax.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: Stream ended unexpectedly
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:516)
	at wiremock.org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at wiremock.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at wiremock.org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at wiremock.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: wiremock.org.apache.commons.fileupload.FileUploadException: Stream ended unexpectedly
	at wiremock.org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:361)
	at com.github.tomakehurst.wiremock.http.multipart.PartParser.parseFrom(PartParser.java:51)
	at com.github.tomakehurst.wiremock.servlet.WireMockHttpServletRequestAdapter.getParts(WireMockHttpServletRequestAdapter.java:279)
	at com.github.tomakehurst.wiremock.verification.LoggedRequest.createFrom(LoggedRequest.java:71)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:88)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:225)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:57)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:69)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:142)
	at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	... 17 more
Caused by: wiremock.org.apache.commons.fileupload.MultipartStream$MalformedStreamException: Stream ended unexpectedly
	at wiremock.org.apache.commons.fileupload.MultipartStream.readHeaders(MultipartStream.java:570)
	at wiremock.org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.findNextItem(FileUploadBase.java:1052)
	at wiremock.org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.&lt;init&gt;(FileUploadBase.java:1017)
	at wiremock.org.apache.commons.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:309)
	at wiremock.org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:333)
	... 38 more</pre>
```

To reproduce, start Wiremock and send this multipart request to any endpoint (replacing the URL for where you have Wiremock running):

```
curl --location --request POST 'http://stubs:8080/test-url' \
--header 'Content-Type: multipart/related; boundary=xxx;' \
--data-raw '--xxx
Content 1
--xxx
Content 2
--xxx--'
```

**Comment by tomakehurst** [comment]
Have you tried testing this in the latest version - 2.34.0?

**Comment by Spencerooni** [comment]
The same issue occurs with 2.34.0.

**Comment by iainardo** [comment]
I encountered similar issues to @Spencerooni, [Wiremock support for multipart/related](https://github.com/wiremock/wiremock/pull/1415#issuecomment-1263529123) , I forked Wiremock 2.28 and made changes to suit our teams use cases. Perhaps the issue I encountered has already been resolved in later revisions ? 

If it helps here, I'm happy to offer a PR. The proposed changes add a compile time dependency on [mimepull](https://github.com/eclipse-ee4j/metro-mimepull).

**Comment by oakstair** [comment]
I created https://github.com/wiremock/wiremock/issues/2002 which i noew realise is a duplicate of this one.

**Comment by calle2010** [comment]
We are seeing the same error during unit tests with Wiremock 2.32.0 to 3.0.0 for "multipart/mixed" content. 

The use case is mocking an OData API. 

```
HTTP 500 Internal Server Error
Response content: {
"cause2":"wiremock.org.apache.commons.fileupload.MultipartStream$MalformedStreamException: Stream ended unexpectedly",
"cause1":"wiremock.org.apache.commons.fileupload.FileUploadException: Stream ended unexpectedly",
"servlet":"com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-2512eaaa",
"cause0":"wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: Stream ended unexpectedly",
"message":"wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: Stream ended unexpectedly",
"url":"/odata/v2/$batch",
"status":"500"
}
```

**Comment by tomakehurst** [comment]
@calle2010 could you provide the full details for reproducing this?

**Comment by calle2010** [comment]
While working on the reproducer I realized that our code sends "\n" as line breaks in the multipart request. When I change to "\r\n" the test works again.

**Comment by tomakehurst** [comment]
OK, that's interesting. Are you running the WireMock server on a Windows host?

**Comment by burcuakkayaa** [comment]
Hi,
I reproduce the problem in Wiremock 3.9.1
Our application sends multipart requests to an external API , and I tried to redirect to wiremock.
and then I faced with the error messages:

```
{"level":"warn","appName":"g-api","agentName":"","correlationId":"c4f66592-0bb7-48f6-8a7b-ce88866edd0d","spanId":"0000000000000000","traceId":"00000000000000000000000000000000","time":"2024-10-15T10:14:26.455Z","sourceLocation":"/app/internal/displayadvert/core/service/upload_image_service.go:42","message":"Could not be uploaded. Error: Status code is not OK while uploading media. Response: <html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\"/>\n<title>Error 500 wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found</title>\n</head>\n<body><h2>HTTP ERROR 500 wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found</h2>\n<table>\n<tr><th>URI:</th><td>/display-ads/images/banner_537_1728976466.png</td></tr>\n<tr><th>STATUS:</th><td>500</td></tr>\n<tr><th>MESSAGE:</th><td>wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found</td></tr>\n<tr><th>SERVLET:</th><td>com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-8c11eee</td></tr>\n<tr><th>CAUSED BY:</th><td>wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found</td></tr>\n<tr><th>CAUSED BY:</th><td>wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found</td></tr>\n</table>\n<h3>Caused by:</h3><pre>wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found\n\tat wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:157)\n\tat wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)\n\tat wiremock.org.eclipse.jetty.server.Server.handle(Server.java:563)\n\tat wiremock.org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)\n\tat wiremock.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)\n\tat wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)\n\tat wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)\n\tat wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)\n\tat wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)\n\tat wiremock.org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)\n\tat wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)\n\tat wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)\n\tat wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)\n\tat wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)\n\tat wiremock.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)\n\tat wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)\n\tat wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)\n\tat wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found\n\tat com.github.tomakehurst.wiremock.http.multipart.FileUpload$FileItemIteratorImpl.&lt;init&gt;(FileUpload.java:617)\n\tat com.github.tomakehurst.wiremock.http.multipart.FileUpload.getItemIterator(FileUpload.java:84)\n\tat com.github.tomakehurst.wiremock.http.multipart.FileUpload.parseRequest(FileUpload.java:108)\n\tat com.github.tomakehurst.wiremock.http.multipart.PartParser.parseFrom(PartParser.java:54)\n\tat com.github.tomakehurst.wiremock.servlet.WireMockHttpServletRequestAdapter.getParts(WireMockHttpServletRequestAdapter.java:283)\n\tat com.github.tomakehurst.wiremock.verification.LoggedRequest.createFrom(LoggedRequest.java:74)\n\tat com.github.tomakehurst.wiremock.stubbing.ServeEvent.of(ServeEvent.java:99)\n\tat com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:58)\n\tat com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:165)\n\tat wiremock.jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)\n\tat wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)\n\tat wiremock.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)\n\tat wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)\n\tat wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)\n\tat wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)\n\tat wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)\n\tat wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)\n\tat wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)\n\tat wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)\n\tat wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)\n\tat wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)\n\tat wiremock.org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:812)\n\tat wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141)\n\t... 18 more\n</pre>\n\n</body>\n</html>"}

```

**Comment by burcuakkayaa** [comment]
hi @tomakehurst , 
unfortunately I can not create a pr because our project does not public, but I can share an example the request which is try to mock. if the example doesn't help you, I can share more detail

`curl --location 'https://xxxx/upload/image' \
--header 'accept: application/json' \
--header 'authorization: Bearer x' \
--header 'Content-Type': 'multipart/form-data'
--header 'cache-control: no-cache' \
--header 'x-correlation-id: ty-ads-web-e6d45d92-bedb-4e58-b285-7676a0dc781f' \
--form 'image=@"image-1230x240.png"'`

**Comment by tomakehurst** [comment]
Please can you share:
* The WireMock version
* Java version
* Platform you're running on
* Startup parameters
* The stub you've defined to receive this request

**Comment by calle2010** [comment]
> OK, that's interesting. Are you running the WireMock server on a Windows host?

Sorry for the super late reply. IIRC it is HTTP standard to use CRLF line endings in the multiparty body. Our code wasn’t following this. 

Wiremock starting with 2.32.0 failed our tests.

**Comment by burcuakkayaa** [comment]
wiremock version - 3.9.1
kotlin version 2.0.20
platform - unfortunately I can not share because we use inhouse project
startup parameter ? could you share about details please?
the stub : actually there is no need stub because the process is broken before the matching mock data. when our application send post request with upload image (I share an example file) as multipart content type, the process is broken due to an error. I'll share error message 

![example-valid-banner-610x150](https://github.com/user-attachments/assets/93eb231c-cccc-42c9-aa8c-b26ae2603e88)

`{"level":"warn","appName":"g-advert-api","agentName":"","correlationId":"353ec332-7676-4477-bbb8-de997e20fe22","spanId":"0000000000000000","traceId":"00000000000000000000000000000000","time":"2024-10-15T09:59:58.069Z","sourceLocation":"/app/internal/displayadvert/core/service/upload_image_service.go:42","message":"Could not be uploaded. Error: Status code is not OK while uploading media. Response: <html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\"/>\n<title>Error 500 wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found</title>\n</head>\n<body><h2>HTTP ERROR 500 wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found</h2>\n<table>\n<tr><th>URI:</th><td>/display-ads/images/banner_537_1728975598.png</td></tr>\n<tr><th>STATUS:</th><td>500</td></tr>\n<tr><th>MESSAGE:</th><td>wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found</td></tr>\n<tr><th>SERVLET:</th><td>com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-fcb4004</td></tr>\n<tr><th>CAUSED BY:</th><td>wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found</td></tr>\n<tr><th>CAUSED BY:</th><td>wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found</td></tr>\n</table>\n<h3>Caused by:</h3><pre>wiremock.jakarta.servlet.ServletException: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found\n\tat wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:157)\n\tat wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)\n\tat wiremock.org.eclipse.jetty.server.Server.handle(Server.java:563)\n\tat wiremock.org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)\n\tat wiremock.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)\n\tat wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)\n\tat wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)\n\tat wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)\n\tat wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)\n\tat wiremock.org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)\n\tat wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)\n\tat wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)\n\tat wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)\n\tat wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)\n\tat wiremock.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)\n\tat wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)\n\tat wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)\n\tat wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: wiremock.org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found\n\tat com.github.tomakehurst.wiremock.http.multipart.FileUpload$FileItemIteratorImpl.&lt;init&gt;(FileUpload.java:617)\n\tat com.github.tomakehurst.wiremock.http.multipart.FileUpload.getItemIterator(FileUpload.java:84)\n\tat com.github.tomakehurst.wiremock.http.multipart.FileUpload.parseRequest(FileUpload.java:108)\n\tat com.github.tomakehurst.wiremock.http.multipart.PartParser.parseFrom(PartParser.java:54)\n\tat com.github.tomakehurst.wiremock.servlet.WireMockHttpServletRequestAdapter.getParts(WireMockHttpServletRequestAdapter.java:283)\n\tat com.github.tomakehurst.wiremock.verification.LoggedRequest.createFrom(LoggedRequest.java:74)\n\tat com.github.tomakehurst.wiremock.stubbing.ServeEvent.of(ServeEvent.java:99)\n\tat com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:58)\n\tat com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:165)\n\tat wiremock.jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)\n\tat wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)\n\tat wiremock.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)\n\tat wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)\n\tat wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)\n\tat wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)\n\tat wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)\n\tat wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)\n\tat wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)\n\tat wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)\n\tat wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)\n\tat wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)\n\tat wiremock.org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:812)\n\tat wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141)\n\t... 18 more\n</pre>\n\n</body>\n</html>"}`

**Comment by tomakehurst** [comment]
@burcuakkayaa I can't replicate the issue based on the curl command you posted. What OS is WireMock running on? And can you share the CLI parameters used when starting it?

**Comment by burcuakkayaa** [comment]
Wiremock is running on Kubernetes with docker image (3.6.6 version)
I'll share example curl which is directed to wiremock, but we can not see unmatching step because of the failure

`curl -X PUT "https://hpc.companyname.com:6780/swift/v1" \
  -H "Content-Type: multipart/form-data" \
  -H "Authorization: Bearer your-token-here" \
  --data-binary "@path/to/your/file" \
  --connect-timeout your-post-timeout-in-seconds`

**Comment by tomakehurst** [comment]
OK so to be clear - you're running WireMock 3.6.6, not 3.9.1?

If that's the case I suggest upgrading before doing any further debugging.

**Comment by burcuakkayaa** [comment]
okey @tomakehurst thanks for your quick answer, I'll try with the last version of wiremock
