### ISSUE TITLE
WireMock shows AMD64 warning in MacBook Pro chip Apple M1 Max

### ISSUE THREAD

**Issue by kamolsavar** [wiremock/wiremock#1988]
# Issue guidelines
When running WireMock with latest image  in local machine in Mac M1 Max  and looked at the Docker desktop dashboard no log is seen.

Also when in terminal :
docker logs -f local-dev-wiremock (container) run no log is displayed the cursor just blinked.

When the status of the wiremock container is check in Docker desktop dashboard it shows an AMD64 warning saying image may have poorer performance or fail, if run via emulation. I think Docker community is aware of that.

**Wiremock**: Version latest
**Failing Test case error**:

The target server failed to respond
org.apache.hc.core5.http.NoHttpResponseException: The target server failed to respond
	at app//org.apache.hc.core5.http.impl.io.DefaultHttpResponseParser.createConnectionClosedException(DefaultHttpResponseParser.java:87)
	at app//org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:243)
	at app//org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:53)
	at app//org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:298)
	at app//org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:175)
	at app//org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
	at app//org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:583)
	at app//org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:212)
	at app//org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:105)
	at app//org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at app//org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at app//org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:182)
	at app//org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at app//org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at app//org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
	at app//org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at app//org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at app//org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at app//org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
	at app//com.github.tomakehurst.wiremock.client.HttpAdminClient.safelyExecuteRequest(HttpAdminClient.java:506)
	at app//com.github.tomakehurst.wiremock.client.HttpAdminClient.executeRequest(HttpAdminClient.java:489)
	at app//com.github.tomakehurst.wiremock.client.HttpAdminClient.executeRequest(HttpAdminClient.java:466)
	at app//com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:146)
	at app//com.github.tomakehurst.w
iremock.client.WireMock.register(WireMock.java:414)
	at app//com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:409)
	at app//com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:115)

## Bug reports

We're a lot more likely to look at and fix bugs that are clearly described and reproduceable. Please including the following details when reporting a bug:

===========================
Are planning to fix this AMD64 issue soon with WireMock Docker issue when running in Mac M1 Max

**Comment by tomakehurst** [comment]
I've just tested 2.34.0 on my M1 Max Macbook and it's showing console logs as expected. I suggest posting a question to the mailing list with some more details of your setup in order to figure out why this isn't working as expected on your machine.

The stacktrace you've posted isn't related to processor architecture. Most likely you've configured the client part of WireMock to point to a host/port that's not open. Again, a mailing list question is the way to go if you need some assistance with this.

Finally, WireMock's Docker image is already published for both `amd` and `arm` architectures (which you can confirm with `docker manifest inspect --verbose wiremock/wiremock:2.34.0`) so it seems your local Docker set up is for some reason selecting the wrong one.

**Comment by kamolsavar** [comment]
Instead of using the our in house mockservice now the wiremock is configured as below in docke-compose.yml  file and it has solved incompatability issue with M1 mac Silicon machine

wiremock:
    image: dockerproxy.xxx.com/wiremock/wiremock:2.34.0
