### ISSUE TITLE
NullPointerException during removal of stubbing having a scenario

### ISSUE THREAD

**Issue by btrummer** [wiremock/wiremock#1999]
Hi.

We use wiremock 2.32.0 as stand-alone server and use the REST API to add and remove stubbings as our automated tests are executed. Sometimes, but rather rare, the removal of a stubbing fails with a NullPointerException and a HTTP 500 status code is returned by the /remove call:

```
java.lang.NullPointerException
    at com.github.tomakehurst.wiremock.stubbing.Scenarios.onStubMappingRemoved(Scenarios.java:73)
    at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.removeMapping(InMemoryStubMappings.java:134)
    at com.github.tomakehurst.wiremock.core.WireMockApp.removeStubMapping(WireMockApp.java:259)
    at com.github.tomakehurst.wiremock.admin.tasks.OldRemoveStubMappingTask.execute(OldRemoveStubMappingTask.java:30)
    at com.github.tomakehurst.wiremock.http.AdminRequestHandler.handleRequest(AdminRequestHandler.java:84)
    at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:69)
    at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:142)
    at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    ...
```
I think what leads to this is:
- our tests are executed multi-threaded, so multiple stubbing calls can happen in parallel.
- each stubbing contains a request header matching on a unique value which is generated for every test case, so the stubbings created by one test don't lead to wrong responses for the other tests.
- each test keeps track of the created stubs and removes them after the test is done. So /remove calls can also happen in parallel.
- some of our stubbings are set up having a scenario (aka stateful stubbing).
- for those stubbings we (currently) use a fixed / hard-coded scenario name but with dynamically generated state keys.

I think, that despite Scenarios.scenarioMap being a ConcurrentHashMap that it's somehow possible that one thread removes a map entry which a different thread wants to get, making it fail with above's NullPointerException (in rare cases).

We'll try to "workaround" this by also using a dynamically created unique scenario name for each test.
However, I think that this is a concurrency bug which should be fixed anyway.

Thanks and best regards.

**Comment by oleg-nenashev** [comment]
After https://github.com/wiremock/wiremock/commit/2f6c9560f1245897263209148dd40f848510318b in 3.0.0-beta-1 the behavior will change. At least it will throw `IllegalStateException` but hard to say with so many code changes including collection types

**Comment by karsie** [comment]
I'm using wiremock-3.13.1 and am currently running into this same issue (with a `IllegalStateException` indeed).

**Comment by karsie** [comment]
I'm also running tests concurrently. My guess is that my scenario name (based on an api-name) is not unique enough and is the same for multiple tests, thus leading into concurrency issues on the scenario store. I'll try to add the test name to the scenario name as well.
