### ISSUE TITLE
Server starts on 8080 port only. 1.30 version

### ISSUE THREAD

**Issue by ggrafu** [wiremock/wiremock#20]
This code throws HttpHostConnectException. However it works fine with 8080 port.

``` java
        WireMockServer wireMockServer = new WireMockServer(wireMockConfig().port(8888)); // works only with 8080 port
        wireMockServer.start();
        Thread.sleep(2000);
        WireMock.reset();
        wireMockServer.stop();
```

I just created empty maven module with 1.30-th wiremock dependency. Issue reproduced on several machines.

Full trace:

``` log
Exception in thread "main" java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8080 refused
    at com.github.tomakehurst.wiremock.client.HttpAdminClient.postJsonAndReturnStatus(HttpAdminClient.java:135)
    at com.github.tomakehurst.wiremock.client.HttpAdminClient.postEmptyBodyAndReturnStatus(HttpAdminClient.java:162)
    at com.github.tomakehurst.wiremock.client.HttpAdminClient.resetMappings(HttpAdminClient.java:78)
    at com.github.tomakehurst.wiremock.client.WireMock.resetMappings(WireMock.java:78)
    at com.github.tomakehurst.wiremock.client.WireMock.reset(WireMock.java:82)
    at main.main(main.java:19)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8080 refused
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:190)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:645)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:480)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
    at com.github.tomakehurst.wiremock.client.HttpAdminClient.postJsonAndReturnStatus(HttpAdminClient.java:127)
    ... 10 more
Caused by: java.net.ConnectException: Connection refused: connect
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
    at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
    at java.net.Socket.connect(Socket.java:529)
    at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
    ... 17 more
```

**Comment by leelanakka** [comment]
Hi tom,
 even though I've added "WireMock.configureFor("localhost", 8888)", still it is showing the same error
