### ISSUE TITLE
Diff for multipart requests is incorrect

### ISSUE THREAD

**Issue by karol-bujacek** [wiremock/wiremock#2047]
I have found a problem with displaying diffs for multipart (form data) requests. Below are three test cases with different behavior.

1. `without_multipart_verify` – the text in the diff looks doubled, but it is still OK – I can see the difference between the expected and the actual request
2. `incorrect_diff_without_withRequestBody` – the verification exception is correctly thrown, but the displayed diff looks identical; it useless (and wrong)
3. `wrong_diff_with_multipart_verify` – the verification exception is correctly thrown too, but the diff is completely wrong: there are data from "actual" in "expected" section.

Please see the POM, unit tests and console output.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>wiremock-bug-sample</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock-jre8-standalone</artifactId>
            <version>2.35.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
```

```java
import com.github.tomakehurst.wiremock.junit.WireMockRule;
import org.junit.Rule;
import org.junit.Test;
import wiremock.org.apache.hc.client5.http.classic.HttpClient;
import wiremock.org.apache.hc.client5.http.classic.methods.HttpPost;
import wiremock.org.apache.hc.client5.http.entity.mime.HttpMultipartMode;
import wiremock.org.apache.hc.client5.http.entity.mime.MultipartEntityBuilder;
import wiremock.org.apache.hc.client5.http.impl.classic.HttpClientBuilder;
import wiremock.org.apache.hc.core5.http.ContentType;

import java.io.IOException;

import static com.github.tomakehurst.wiremock.client.WireMock.aMultipart;
import static com.github.tomakehurst.wiremock.client.WireMock.containing;
import static com.github.tomakehurst.wiremock.client.WireMock.okJson;
import static com.github.tomakehurst.wiremock.client.WireMock.post;
import static com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor;
import static com.github.tomakehurst.wiremock.client.WireMock.urlPathEqualTo;
import static com.github.tomakehurst.wiremock.client.WireMock.verify;

public class WiremockTest {
    @Rule
    public WireMockRule wireMockRule = new WireMockRule(8888);

    @Test
    public void without_multipart_verify() throws IOException {
        createStub();
        execute();

        verify(
                postRequestedFor(urlPathEqualTo("/api/storage/file"))
                        .withHeader("content-type", containing("multipart/form-data"))
                        .withRequestBody(containing("Content-Disposition: form-data;"))
                        .withRequestBody(containing("File with different content"))
                        .withRequestBody(containing("\"id\":\"this-value-is-completely-wrong\""))
        );
    }

    @Test
    public void incorrect_diff_without_withRequestBody() throws IOException {
        createStub();
        execute();

        verify(
                postRequestedFor(urlPathEqualTo("/api/storage/file"))
                        .withHeader("content-type", containing("multipart/form-data"))
                        .withRequestBodyPart(aMultipart()
                                .withName("file")
                                .withBody(containing("File with different content"))
                                .build())
                        .withRequestBodyPart(aMultipart()
                                .withName("properties")
                                .withBody(containing("\"id\":\"this-value-is-completely-wrong\""))
                                .build())
        );
    }

    @Test
    public void wrong_diff_with_multipart_verify() throws IOException {
        createStub();
        execute();

        verify(
                postRequestedFor(urlPathEqualTo("/api/storage/file"))
                        .withHeader("content-type", containing("multipart/form-data"))
                        .withRequestBody(containing("Content-Disposition: form-data;"))
                        .withRequestBodyPart(aMultipart()
                                .withName("file")
                                .withBody(containing("File with different content"))
                                .build())
                        .withRequestBodyPart(aMultipart()
                                .withName("properties")
                                .withBody(containing("\"id\":\"this-value-is-completely-wrong\""))
                                .build())
        );
    }

    private void createStub() {
        wireMockRule.stubFor(
                post("/api/storage/file")
                        .withMultipartRequestBody(aMultipart()
                                .withName("file"))
                        .withMultipartRequestBody(aMultipart()
                                .withName("properties"))
                        .willReturn(okJson("{}"))
        );
    }

    private void execute() throws IOException {
        byte[] bytes = "Testing file".getBytes();
        MultipartEntityBuilder builder = MultipartEntityBuilder.create();
        builder.setMode(HttpMultipartMode.STRICT);
        builder.addBinaryBody(
                "file",
                bytes,
                ContentType.DEFAULT_BINARY,
                "filename.txt"
        );
        builder.addTextBody("properties", "{\"id\":\"12345\"}", ContentType.APPLICATION_JSON);

        HttpPost post = new HttpPost("http://localhost:8888/api/storage/file");
        post.setEntity(builder.build());

        HttpClient client = HttpClientBuilder.create().build();
        client.execute(post);
    }
}
```

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.example:wiremock-bug-sample >-------------------
[INFO] Building wiremock-bug-sample 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ wiremock-bug-sample ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ wiremock-bug-sample ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ wiremock-bug-sample ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/karol/sandbox/wiremock-bug-sample/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ wiremock-bug-sample ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ wiremock-bug-sample ---
[INFO] Surefire report directory: /home/karol/sandbox/wiremock-bug-sample/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running WiremockTest
Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.751 sec <<< FAILURE!
without_multipart_verify(WiremockTest)  Time elapsed: 0.684 sec  <<< FAILURE!
com.github.tomakehurst.wiremock.client.VerificationException: No requests exactly matched. Most similar request was:  expected:<
POST
/api/storage/file

content-type: multipart/form-data; charset=ISO-8859-1; boundary=b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA

--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA
Content-Disposition: form-data; name="file"; filename="filename.txt"
Content-Type: application/octet-stream

Testing file
--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA
Content-Disposition: form-data; name="properties"
Content-Type: application/json; charset=UTF-8

{"id":"12345"}
--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA--

File with different content
"id":"this-value-is-completely-wrong"> but was:<
POST
/api/storage/file

content-type: multipart/form-data; charset=ISO-8859-1; boundary=b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA

--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA
Content-Disposition: form-data; name="file"; filename="filename.txt"
Content-Type: application/octet-stream

Testing file
--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA
Content-Disposition: form-data; name="properties"
Content-Type: application/json; charset=UTF-8

{"id":"12345"}
--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA--

--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA
Content-Disposition: form-data; name="file"; filename="filename.txt"
Content-Type: application/octet-stream

Testing file
--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA
Content-Disposition: form-data; name="properties"
Content-Type: application/json; charset=UTF-8

{"id":"12345"}
--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA--

--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA
Content-Disposition: form-data; name="file"; filename="filename.txt"
Content-Type: application/octet-stream

Testing file
--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA
Content-Disposition: form-data; name="properties"
Content-Type: application/json; charset=UTF-8

{"id":"12345"}
--b6OjUYrfqhKVjoPy6n_RcgzoHgC4Oc5r350jA--
>
	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedRequestPattern(VerificationException.java:38)
	at com.github.tomakehurst.wiremock.client.WireMock.verificationExceptionForNearMisses(WireMock.java:680)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:670)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:646)
	at com.github.tomakehurst.wiremock.client.WireMock.verify(WireMock.java:687)
	at WiremockTest.without_multipart_verify(WiremockTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:67)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

incorrect_diff_without_withRequestBody(WiremockTest)  Time elapsed: 0.026 sec  <<< FAILURE!
com.github.tomakehurst.wiremock.client.VerificationException: No requests exactly matched. Most similar request was:  expected:<
POST
/api/storage/file

content-type: multipart/form-data; charset=ISO-8859-1; boundary=hGLFpFdtYsMeW8vzEBsq-CZkk11-yzRp2N


> but was:<
POST
/api/storage/file

content-type: multipart/form-data; charset=ISO-8859-1; boundary=hGLFpFdtYsMeW8vzEBsq-CZkk11-yzRp2N


>
	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedRequestPattern(VerificationException.java:38)
	at com.github.tomakehurst.wiremock.client.WireMock.verificationExceptionForNearMisses(WireMock.java:680)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:670)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:646)
	at com.github.tomakehurst.wiremock.client.WireMock.verify(WireMock.java:687)
	at WiremockTest.incorrect_diff_without_withRequestBody(WiremockTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:67)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

wrong_diff_with_multipart_verify(WiremockTest)  Time elapsed: 0.021 sec  <<< FAILURE!
com.github.tomakehurst.wiremock.client.VerificationException: No requests exactly matched. Most similar request was:  expected:<
POST
/api/storage/file

content-type: multipart/form-data; charset=ISO-8859-1; boundary=uK-xsW7ETrKH0GDqx47JF3gV8A0bHpu

--uK-xsW7ETrKH0GDqx47JF3gV8A0bHpu
Content-Disposition: form-data; name="file"; filename="filename.txt"
Content-Type: application/octet-stream

Testing file
--uK-xsW7ETrKH0GDqx47JF3gV8A0bHpu
Content-Disposition: form-data; name="properties"
Content-Type: application/json; charset=UTF-8

{"id":"12345"}
--uK-xsW7ETrKH0GDqx47JF3gV8A0bHpu--


> but was:<
POST
/api/storage/file

content-type: multipart/form-data; charset=ISO-8859-1; boundary=uK-xsW7ETrKH0GDqx47JF3gV8A0bHpu

--uK-xsW7ETrKH0GDqx47JF3gV8A0bHpu
Content-Disposition: form-data; name="file"; filename="filename.txt"
Content-Type: application/octet-stream

Testing file
--uK-xsW7ETrKH0GDqx47JF3gV8A0bHpu
Content-Disposition: form-data; name="properties"
Content-Type: application/json; charset=UTF-8

{"id":"12345"}
--uK-xsW7ETrKH0GDqx47JF3gV8A0bHpu--


>
	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedRequestPattern(VerificationException.java:38)
	at com.github.tomakehurst.wiremock.client.WireMock.verificationExceptionForNearMisses(WireMock.java:680)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:670)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:646)
	at com.github.tomakehurst.wiremock.client.WireMock.verify(WireMock.java:687)
	at WiremockTest.wrong_diff_with_multipart_verify(WiremockTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:67)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   without_multipart_verify(WiremockTest): No requests exactly matched. Most similar request was:  expected:<(..)
  incorrect_diff_without_withRequestBody(WiremockTest): No requests exactly matched. Most similar request was:  expected:<(..)
  wrong_diff_with_multipart_verify(WiremockTest): No requests exactly matched. Most similar request was:  expected:<(..)

Tests run: 3, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.912 s
[INFO] Finished at: 2022-12-17T02:12:57+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project wiremock-bug-sample: There are test failures.
[ERROR]
[ERROR] Please refer to /home/karol/sandbox/wiremock-bug-sample/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by karol-bujacek** [comment]
After debugging the wiremock code I have found several places where the wrong behavior can be seen.

Both `expected` and `actual` strings are created in `JUnitStyleDiffRenrerer`, method `render(Diff)` (https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/verification/diff/JUnitStyleDiffRenderer.java#L27)

In the list of lines I can see instance of `SelectionDelimiter`, but its value is equal to `"[Multipart request body]"`. (Actually there are two such instances because I used `.withRequestBodyPart` twice in my tests, but I hope it is not important for the issue debugging.)

Why the instance has such value?

Because the request is not recognized as a multipart. See `Diff` class, method `getLines()` (https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java#L182)
It means that this instance of `LoggedRequest` has value of property `multiparts` equal to `null`. 

It is weird.  The output of `request.getHeaders()` looks like this – content type is multipart/form-data.
```
its-apikey: [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
Content-Length: [365]
Content-Type: [multipart/form-data; boundary=KXtUuwEPOUZQIc-ZC7T6HwfLCtT-tSamiErKJj]
Host: [localhost:37629]
Connection: [keep-alive]
User-Agent: [Apache-HttpClient/4.5.10 (Java/1.8.0_201)]
Accept-Encoding: [gzip,deflate]
```

This leads me to the `WireMock` class, method `verificationExceptionForNearMisses` (https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java#L675)

**Comment by karol-bujacek** [comment]
(sorry for close & reopen, I hit the close button by accident)

In that method I can see that diff is created from the `requestPattern` and the `nearMisses.get(0).getRequest()`.

Well, what is the second object passed to the `Diff` constructor? It is the response from the `HttpAdminClient`, see method `findAllNearMissesFor` in the same class (https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java#L861).

This request is not multipart, at least `isMultipart` method is saying that. But from the `nearMisses.get(0).getRequest()` it is clear that it has content type multipart/form-data and all the data in the body (see with `toString` method in debugger).

This looks like a problem, right?

Where does this instance of `LoggedRequest` came from?

I have set up debugger to log method hits and found that there are two different invocations of `LoggedRequest.createFrom`:

1. With the actual body sent from my test, call to `/api/storage/file` (which is mock REST endpoint),
2. a formatted JSON data, calls to `/requests/count` and `/near-misses/request-pattern`. 

The wiremock server is  sending formatted JSON, not multipart content, and the `multiparts` property is not set correctly. See this line: [LoggedRequest.java#L72](https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/verification/LoggedRequest.java#L72)

Currently I am not able to find why there is a problem with the diff output, but I suspect that request handling and managing multipart content and `multiparts` property is somehow broken.

**Comment by karol-bujacek** [comment]
The problematic `LoggedRequest` instance is created from the JSON data, see 
[LoggedRequest.java#L77](https://github.com/wiremock/wiremock/blob/cdb6d6d3b1c9f1ac53302c93622a06c32ce06802/src/main/java/com/github/tomakehurst/wiremock/verification/LoggedRequest.java#L77).

In this case, the value of `multiparts` is always null because parts / multiparts is annotated using `@JsonIgnore`, see [LoggedRequest.java#L293](https://github.com/wiremock/wiremock/blob/cdb6d6d3b1c9f1ac53302c93622a06c32ce06802/src/main/java/com/github/tomakehurst/wiremock/verification/LoggedRequest.java#L293).

These data should be present in the JSON data, annotation should be changed to `@JsonProperty("multiparts")`.

This change also requires code to be changed at several places:

- `Part` should be JSON serializable and deserializable. This can be done by annotating `Part` interface using `@JsonDeserialize(as = JsonPart.class)`, see [Request.java#L25](https://github.com/wiremock/wiremock/blob/cdb6d6d3b1c9f1ac53302c93622a06c32ce06802/src/main/java/com/github/tomakehurst/wiremock/http/Request.java#L25)

- A proposed `JsonPart` class holds all the data:

```java
package com.github.tomakehurst.wiremock.http.multipart;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.github.tomakehurst.wiremock.http.Body;
import com.github.tomakehurst.wiremock.http.HttpHeader;
import com.github.tomakehurst.wiremock.http.HttpHeaders;
import com.github.tomakehurst.wiremock.http.Request;

@JsonIgnoreProperties(ignoreUnknown = true)
public class JsonPart implements Request.Part {
    private final String name;
    private final HttpHeaders httpHeaders;
    private final Body body;

    @JsonCreator
    public JsonPart(
            @JsonProperty("name") String name,
            @JsonProperty("headers") HttpHeaders httpHeaders,
            @JsonProperty("body") Body body
    ) {
        this.name = name;
        this.httpHeaders = httpHeaders;
        this.body = body;
    }

    @Override
    @JsonProperty
    public String getName() {
        return this.name;
    }

    @Override
    @JsonIgnore
    public HttpHeader getHeader(String name) {
        return this.httpHeaders.getHeader(name);
    }

    @Override
    @JsonProperty
    public HttpHeaders getHeaders() {
        return this.httpHeaders;
    }

    @Override
    @JsonProperty
    public Body getBody() {
        return this.body;
    }
}
```

- In order to convert `Part` to JSON, Jackson annotation `@JsonIgnoreProperties` should be add to `FileItemPartAdapter` class ([FileItemPartAdapter.java#L29](https://github.com/wiremock/wiremock/blob/cdb6d6d3b1c9f1ac53302c93622a06c32ce06802/src/main/java/com/github/tomakehurst/wiremock/http/multipart/FileItemPartAdapter.java#L29)), `@JsonIgnore` annotation to `getHeader` method and `@JsonProperty` annotations to `getName`, `getHeaders` and `getBody` methods in the `FileItemPartAdapter` class.

- Also `Body`, see [Body.java#L30](https://github.com/wiremock/wiremock/blob/cdb6d6d3b1c9f1ac53302c93622a06c32ce06802/src/main/java/com/github/tomakehurst/wiremock/http/Body.java#L30), should be serialized and deserialized to JSON. This can be done with a new constructor
```java
  @JsonCreator
  public Body(
          @JsonProperty("content") String content,
          @JsonProperty("binary") boolean binary,
          @JsonProperty("json") boolean json
  ) {
    this.content = decodeBase64(content);
    this.binary = binary;
    this.json = json;
  }
```
and `@JsonIgnoreProperties(ignoreUnknown = true)` class annotation and `@JsonProprety("content") public String asBase64`, `@JsonProperty("binary") public boolean isBinary` and `@JsonProperty("json") public boolean isJson` method annotations.

After these updates diff operation knows that the request is multipart and knows all the parts.

The problem is, however, that there are nested loops in `Diff.getLines` method, see [Diff.java#L181](https://github.com/wiremock/wiremock/blob/cdb6d6d3b1c9f1ac53302c93622a06c32ce06802/src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java#L181) and [#L185](https://github.com/wiremock/wiremock/blob/cdb6d6d3b1c9f1ac53302c93622a06c32ce06802/src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java#L181).  In case there are two properties, in diff result we can find two false positives – property A do not match property B and property B do not match property A.

**Comment by karol-bujacek** [comment]
Uh, oh. I have noticed that the test is working correctly in some cases and causing false fails in other cases.

If I use this block in my test:
```java
        verify(
                postRequestedFor(urlPathEqualTo("/api/storage/file"))
                        .withPort(wireMockRule.port())
                        .withHeader("content-type", containing("multipart/form-data"))
                        .withRequestBody(containing("Content-Disposition: form-data;"))
                        .withAllRequestBodyParts(aMultipart()
                                .withName("file")
                                .withBody(containing("Testing file"))
                                )
                        .withAllRequestBodyParts(aMultipart()
                                .withName("properties")
                                .withBody(containing("\"UidReference\":\"73a9e788-30b3-47d1-ad95-1e848dfcd47b\""))
                                )
        );
```
then the diff output is wrong and test fails (this is part related to the multipart tests):

![screenshot_20221219-165153](https://user-images.githubusercontent.com/4030734/208466212-6a8496c9-38ff-4711-a554-df1e7e5153b0.png)

Notice the cross diffs, [properties] with expected file, [file] with expected properties.

If the test code is changed and `.withRequestBodyPart` is used instead of `.withAllRequestBodyParts`, then:
1. the test is passing for correct data.
2. test is failing for one invalid value (here I inserted string `invalid` before the UUID string), I can see the problem, but tie diff for another part is completely wrong:

![screenshot_20221219-165945](https://user-images.githubusercontent.com/4030734/208467743-68f26678-18b3-4984-b155-a2bd8b5de80c.png)
5. test is failing for two invalid values (notice `"Testing file"` changed to `"Testing filefilefile"`) and there are multiple wrong expected values:

![screenshot_20221219-170643](https://user-images.githubusercontent.com/4030734/208469016-88bc50f5-4435-4940-a424-8612dff18602.png)

It is completely messed up, but still useful. If the test is passing, then data are OK. If something is wrong, then you will see some information and you hopefully will be able to fix your code.

The last remaining problem is why the wiremock is telling us that it expects named part with wrong data? I.e., why and how this code
```java
                        .withRequestBodyPart(aMultipart()
                                .withName("properties")
                                .withBody(containing("\"UidReference\":\"invalid 73a9e788-30b3-47d1-ad95-1e848dfcd47b" +
                                        "\""))
                                .build())
```
may produce
```
[properties]

Content-Disposition [contains] : name="file"

Testing filefilefile

[/properties]
```
and code
```java
                        .withRequestBodyPart(aMultipart()
                                .withName("file")
                                .withBody(containing("Testing filefilefile"))
                                .build())
```
may produce
```
[file]

Content-Disposition [contains] : name="properties"

"UidReference":"invalid 73a9e788-30b3-47d1-ad95-1e848dfcd47b"

[/file]
```
?
