### ISSUE TITLE
withBodyFile throws HandlebarsException for zip based archive format

### ISSUE THREAD

**Issue by FieteO** [wiremock/wiremock#2055]
### Which version of WireMock you're using
I am using `com.github.tomakehurst:wiremock-jre8-standalone:2.33.0`.

### How you're starting and configuring WireMock, including configuration or CLI the command line
Wiremock is launched as part of integration tests in a Java Spring Boot application via `@AutoConfigureWireMock()`.

### A failing test case that demonstrates the problem
I am unfortunately unable to provide a reproducible test case since the file that is producing the error is proprietary.
The stub is defined as:
``` java
WireMock.stubFor(
    WireMock.get(WireMock.urlEqualTo("/api/myendpoint"))
        .willReturn(
            WireMock.aResponse()
                .withHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_OCTET_STREAM_VALUE)
                .withBodyFile("archiveLikeFile.smth")));
```
The stacktrace is:
```
wiremock.com.google.common.util.concurrent.UncheckedExecutionException: wiremock.com.github.jknack.handlebars.HandlebarsException: inline@508cb789:1:2: found: '�'
    {{�t3
J
3�d�(��ӠK~����gݷ����|9���-X�S�����:ۛR��Z�B,�9u�POKAJ�L�R�u>+�u�
      ^

        at wiremock.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
        at wiremock.com.google.common.cache.LocalCache.get(LocalCache.java:3966)
        at wiremock.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
        at com.github.tomakehurst.wiremock.extension.responsetemplating.TemplateEngine.getTemplate(TemplateEngine.java:96)
        at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.transform(ResponseTemplateTransformer.java:119)
        at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.applyTransformations(InMemoryStubMappings.java:102)
        at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:84)
        at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:226)
        at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:57)
        at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:69)
        at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:142)
        at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at wiremock.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
        at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
        at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
        at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at wiremock.org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
        at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:516)
        at wiremock.org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at wiremock.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at wiremock.org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at wiremock.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:829)
    Caused by: wiremock.com.github.jknack.handlebars.HandlebarsException: inline@508cb789:1:2: found: '�'
    {{�t3
J
3�d�(��ӠK~����gݷ����|9���-X�S�����:ۛR��Z�B,�9u�POKAJ�L�R�u>+�u�
      ^

        at wiremock.com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
        at wiremock.com.github.jknack.handlebars.internal.antlr.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at wiremock.com.github.jknack.handlebars.internal.HbsParserFactory$2.notifyListeners(HbsParserFactory.java:138)
        at wiremock.com.github.jknack.handlebars.internal.antlr.Lexer.nextToken(Lexer.java:144)
        at wiremock.com.github.jknack.handlebars.internal.antlr.BufferedTokenStream.fetch(BufferedTokenStream.java:169)
        at wiremock.com.github.jknack.handlebars.internal.antlr.BufferedTokenStream.sync(BufferedTokenStream.java:152)
        at wiremock.com.github.jknack.handlebars.internal.antlr.BufferedTokenStream.consume(BufferedTokenStream.java:136)
        at wiremock.com.github.jknack.handlebars.internal.antlr.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:537)
        at wiremock.com.github.jknack.handlebars.internal.antlr.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
        at wiremock.com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:225)
        at wiremock.com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:174)
        at wiremock.com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:88)
        at wiremock.com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:54)
        at wiremock.com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:575)
        at wiremock.com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:535)
        at wiremock.com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:515)
        at com.github.tomakehurst.wiremock.extension.responsetemplating.HandlebarsOptimizedTemplate.uncheckedCompileTemplate(HandlebarsOptimizedTemplate.java:56)
        at com.github.tomakehurst.wiremock.extension.responsetemplating.HandlebarsOptimizedTemplate.<init>(HandlebarsOptimizedTemplate.java:51)
        at com.github.tomakehurst.wiremock.extension.responsetemplating.TemplateEngine.lambda$getTemplate$0(TemplateEngine.java:96)
        at wiremock.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
        at wiremock.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
        at wiremock.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
        at wiremock.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
        at wiremock.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        ... 40 common frames omitted
```
Again I am sorry that I can't provide a fully reproducable example, but maybe the stack trace is enough to hint at the underlying problem. The file format is basically a zip archive and can be extracted as such.

**Comment by kad-orhung** [comment]
I have the same exception but with a PDF and also using.
```java
    wireMockWrapper.registerStub(WireMock.get(urlPathMatching("/planfiles/.*\\.pdf"))
        .atPriority(1)
        .willReturn(aResponse()
            .withHeader("Content-Type", "application/pdf")
            .withStatus(200)
            .withBodyFile(root + "{{request.path.[1]}}")));
```

As a workaround I solved it by returning a hardcoded string with `.withBody("Dummy PDF")` since I don't care about the content. However it would be nice if this problem is fixed.
