### ISSUE TITLE
Java 21 support

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock#2149]
### Proposal

Java 21 LTS is coming out soon, and it would be great to ensure that WireMock is fully compatible with it

### References

- https://openjdk.org/projects/jdk/21/
- https://www.infoq.com/news/2023/03/java-20-so-far/

**Comment by SimonVerhoeven** [comment]
The Gradle wrapper will also need to be updated to 8.4.

**Comment by mikebell90** [comment]
Are there known issues ? It seems problematic to wait a year until after java 21 comes out for an official wiremock 4 support

**Comment by matiwinnetou** [comment]
Doesn't seem compatible...

works with JDK 17 but fails with JDK 21



```
	testImplementation("org.wiremock:wiremock:3.3.1")
```

Error I am getting:
```
java.lang.IncompatibleClassChangeError: class org.eclipse.jetty.http2.server.HttpChannelOverHTTP2 has interface org.eclipse.jetty.server.HttpChannel as super class
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.eclipse.jetty.http2.server.AbstractHTTP2ServerConnectionFactory.<init>(AbstractHTTP2ServerConnectionFactory.java:82)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory.<init>(HTTP2ServerConnectionFactory.java:53)
	at org.eclipse.jetty.http2.server.HTTP2CServerConnectionFactory.<init>(HTTP2CServerConnectionFactory.java:53)
	at org.eclipse.jetty.http2.server.HTTP2CServerConnectionFactory.<init>(HTTP2CServerConnectionFactory.java:48)
	at com.github.tomakehurst.wiremock.jetty11.Jetty11HttpServer.createHttpConnector(Jetty11HttpServer.java:53)
	at com.github.tomakehurst.wiremock.jetty.JettyHttpServer.<init>(JettyHttpServer.java:89)
	at com.github.tomakehurst.wiremock.jetty11.Jetty11HttpServer.<init>(Jetty11HttpServer.java:44)
	at com.github.tomakehurst.wiremock.jetty.JettyHttpServerFactory.buildHttpServer(JettyHttpServerFactory.java:31)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:81)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:123)
	at org.cardano.foundation.voting.api.BaseTest.setUp(BaseTest.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.lang.NullPointerException: Cannot invoke "com.github.tomakehurst.wiremock.WireMockServer.stop()" because "this.wireMockServer" is null
		at org.cardano.foundation.voting.api.BaseTest.tearDown(BaseTest.java:230)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
		at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
		... 1 more
```

**Comment by marcindabrowski** [comment]
@matiwinnetou  are you sure that in your project you are not importing any bom file? For example I had the same error with Spring Boot 3.2 because in their bom there is Jetty 12, which is not compatible with Jetty 11 used by Wiremock?

**Comment by seroandone** [comment]
@marcindabrowski how did you end up excluding springboot jetty bom? I am facing the same issue

**Comment by sankarav** [comment]
thanks for that tip @marcindabrowski  i was able to resolve it, here is what i did, added the following segment to my pom.xml

```xml

<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-bom</artifactId>
      <version>11.0.18</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

```

This works, because, maven honors <dependencyManagement> in the local pom.xml over the parent pom, or its parent.

Note: I am using,

- java 21
- springboot 3.2.0
- wiremock 3.3.1

Documenting failure attempts,

1. tried changing just the value of <jetty.version> to 11.0.18 in <properties> of my pom.xml, however that wont work as there is another bom `org.eclipse.jetty.ee10` that references the same <jetty.version> property, which doesnt have the same versioning.

Please keep comment if there was a better resolution

**Comment by seroandone** [comment]
thanks for that tip @marcindabrowski i was able to resolve it, here is what i did, added the following segment to my pom.xml

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-bom</artifactId>
      <version>11.0.18</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
```

This works, because, maven honors in the local pom.xml over the parent pom, or its parent.

Note: I am using,

- java 21
- springboot 3.2.0
- wiremock 3.3.1

Documenting failure attempt,

tried changing just the value of `<jetty.version>` to `11.0.18` in of my `pom.xml`, however that wont work as there is another bom `org.eclipse.jetty.ee10` that references the same `<jetty.version>` property, which doesn't have the same versioning.

Please comment if there was a better resolution

**Comment by marcindabrowski** [comment]
I'm using Gradle, and for me this helped:

```kotlin
configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.eclipse.jetty") {
            useVersion("11.0.18")
            because("Jetty 12.x.x from Spring Boot 3.2.x is incompatible with Wiremock 3.3.x.")
        }
    }
}
```

But it only works when you are importing Spring bom like this:

```kotlin
implementation(platform("org.springframework.boot:spring-boot-dependencies:3.2.0"))
```

If you are using `io.spring.dependency-management` Gradle plugin it will not work, becuase in Spring Boot 3.2.0 they added new Jetty depenedency [jetty-ee10-bom](https://mvnrepository.com/artifact/org.eclipse.jetty.ee10/jetty-ee10-bom), which do not have 11 version, and with this plugin you can just override Spring bom property like this:

```kotlin
ext["jetty.version"] = "11.0.18"
```

So the only solution I found is to remove this plugin and import Spring Bom in Gradle way.

**Comment by Saljack** [comment]
These mentioned errors are not connected to Java 21 but to library mismatch (Jetty in WireMock and Spring Booot). 
But do not override jetty version or other hacky things. Just use `wiremock-standalone`:
```xml
<dependency>
    <groupId>org.wiremock</groupId>
    <artifactId>wiremock-standalone</artifactId>
    <version>3.3.1</version>
    <scope>test</scope>
</dependency>
```
This version shades all dependencies and you do not need to change anything.

**Comment by marcelstoer** [comment]
AFAIU the official recommendation is to use `wiremock-jetty12` (instead of standalone) as per https://github.com/wiremock/wiremock/issues/2395#issuecomment-2033000623.

**Comment by koppor** [comment]
Handlebars needs to be updated from 4.3.1 to 4.4.0. Their Java Module System Fix is included in 4.4.0 (and not 4.3.1) - https://github.com/jknack/handlebars.java/issues/1018.

Using handlebars 4.4.0 is blocked by Java 11 compatibility of Wiremock. See https://github.com/wiremock/wiremock/issues/2874.

When using Gradle, one can use [Extra Java Module Info Gradle plugin](https://github.com/gradlex-org/extra-java-module-info#extra-java-module-info-gradle-plugin) with following configuration:

```kotlin
plugins {
 ...
    id("org.gradlex.extra-java-module-info")
    id("org.gradlex.java-module-testing")
}

extraJavaModuleInfo {
    failOnMissingModuleInfo = false
    failOnAutomaticModules = false
    deriveAutomaticModuleNamesFromFileNames = true

    module("org.wiremock:wiremock", "wiremock") {
        overrideModuleName()
        patchRealModule()
        exportAllPackages()

        requires("wiremock.slf4j.spi.shim")
        requires("com.fasterxml.jackson.core")
        requires("com.fasterxml.jackson.databind")
        requires("com.fasterxml.jackson.datatype.jsr310")
        requires("com.google.common")
        requires("commons.fileupload")
        requires("org.eclipse.jetty.server")
        requires("org.eclipse.jetty.servlet")
        requires("org.eclipse.jetty.servlets")
        requires("org.eclipse.jetty.webapp")
        requires("org.eclipse.jetty.proxy")
        requires("org.eclipse.jetty.http2.server")
        requires("org.eclipse.jetty.alpn.server")
        requires("org.eclipse.jetty.alpn.java.server")
        requires("org.eclipse.jetty.alpn.java.client")
        requires("org.eclipse.jetty.alpn.client")
        requires("java.xml")
        requires("org.custommonkey.xmlunit")
        requires("org.slf4j")
        requires("org.xmlunit")

        uses("com.github.tomakehurst.wiremock.extension.Extension")

        // workaround for https://github.com/wiremock/wiremock/issues/2874
        mergeJar("com.github.jknack:handlebars")
        mergeJar("com.github.jknack:handlebars-helpers")

        // Required to provide package "wiremock.org.slf4j.helpers"
        mergeJar("com.github.koppor:wiremock-slf4j-shim")
    }
}

javaModuleTesting.whitebox(testing.suites["test"]) {
    requires.add("wiremock")
    requires.add("wiremock.slf4j.spi.shim")
}

dependencies {
...
    testImplementation("org.wiremock:wiremock:3.13.0")
    implementation("com.github.koppor:wiremock-slf4j-shim:main-SNAPSHOT")
    testImplementation("com.github.koppor:wiremock-slf4j-spi-shim:main-SNAPSHOT")
	    implementation("com.github.jknack:handlebars:4.3.1") {
        exclude(group = "org.mozilla", module = "rhino")
    }
    implementation("com.github.jknack:handlebars-helpers:4.3.1") {
        exclude(group = "org.mozilla", module = "rhino")
        exclude(group = "org.apache.commons", module = "commons-lang3")
    }
}
```

The shims are availble at

- https://github.com/koppor/wiremock-slf4j-spi-shim
- https://github.com/koppor/wiremock-slf4j-shim

Maybe more "requires" are needed. Inspiration at https://github.com/wiremock/wiremock/blob/4c0c83c89554c4f927b6d7edb7cedff630161b7a/build.gradle#L49.

I am discussing (at https://github.com/gradlex-org/extra-java-module-info/issues/134#issuecomment-2956556651) how to change `implementation` to `testImplementation` in the cases here.

**Comment by koppor** [comment]
Full example here: https://github.com/koppor/wiremock-mwe
