### ISSUE TITLE
Flaky Test: ResponseTemplateTransformerTest > canHandleALargeTemplateReasonablyFast() 

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock#2259]
### Summary

Higher timeout is needed, it seems

```
ResponseTemplateTransformerTest > canHandleALargeTemplateReasonablyFast() FAILED
    java.lang.AssertionError: 
    Expected: a value less than <PT5S>
         but: <PT5.440965S> was greater than <PT5S>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformerTest.canHandleALargeTemplateReasonablyFast(ResponseTemplateTransformerTest.java:1026)
```

**Comment by prithvitewatia** [comment]
@oleg-nenashev Can you please guide me on this issue. I would like to work on it.
