### ISSUE TITLE
Support for Jetty 12

### ISSUE THREAD

**Issue by mdindoffer** [wiremock/wiremock#2317]
### Proposal

Latest Wiremock 3.0.0-beta-10 does not work with Jetty 12.
`IncompatibleClassChangeError` is thrown when trying to create Wiremock server:

```
java.lang.IncompatibleClassChangeError: class org.eclipse.jetty.http2.server.HttpChannelOverHTTP2 has interface org.eclipse.jetty.server.HttpChannel as super class

	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.eclipse.jetty.http2.server.AbstractHTTP2ServerConnectionFactory.<init>(AbstractHTTP2ServerConnectionFactory.java:80)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory.<init>(HTTP2ServerConnectionFactory.java:53)
	at org.eclipse.jetty.http2.server.HTTP2CServerConnectionFactory.<init>(HTTP2CServerConnectionFactory.java:53)
	at org.eclipse.jetty.http2.server.HTTP2CServerConnectionFactory.<init>(HTTP2CServerConnectionFactory.java:48)
	at com.github.tomakehurst.wiremock.jetty11.Jetty11HttpServer.createHttpConnector(Jetty11HttpServer.java:53)
	at com.github.tomakehurst.wiremock.jetty.JettyHttpServer.<init>(JettyHttpServer.java:89)
	at com.github.tomakehurst.wiremock.jetty11.Jetty11HttpServer.<init>(Jetty11HttpServer.java:44)
	at com.github.tomakehurst.wiremock.jetty.JettyHttpServerFactory.buildHttpServer(JettyHttpServerFactory.java:31)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:75)
	at com.example.common.WireMockTest.setUp(WireMockTest.java:50)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	Suppressed: java.lang.NullPointerException: Cannot invoke "com.github.tomakehurst.wiremock.WireMockServer.stop()" because "this.wireMockServer" is null
		at com.example.common.WireMockTest.stopMockServer(WireMockTest.java:58)
		... 3 more
```

IMHO this is tilting at windmills. Wiremock should **shade** all Jetty dependencies it needs, so that no classpath fighting is possible and consumers are free to use any Jetty version in their projects.

### Reproduction steps

- Add Jetty 12  (EE10) to classpath
- Create WireMockServer `new WireMockServer(options().dynamicPort())`

**Comment by oleg-nenashev** [comment]
I think it is kind of "as designed", because shading Jetty is not enough

My recommendation is to use the Testcontainers module for tests, because in such a case WireMock will be running in a container, hence no conflict 

Does it look feasible in your case?

**Comment by mdindoffer** [comment]
Feasible? Yes. Ideal? No. 
While I applaud to what Testcontainers do, they are kind of slow compared to regular runtime.
Unit tests need to be fast. Blazingly fast. Otherwise people avoid running them.
Plus it's a mess to set up DnD for CI builds with Testcontainers.

**Comment by oleg-nenashev** [comment]
I agree that Testcontainers might be slower in some use-cases, but it might be also faster for others with proper caching.
Anyway, we indeed want to have Jetty 12 support integrated, I will add it to the roadmap. 

## Technical implementation

- We leverage the Web server provider extension and expand it to 
- Detach Jetty 11 to an extension JAR while keeping it in the standalone bundle
- Offer Jetty 12 extension, probably taking it from the classpath

Will need decisions from @tomakehurst IMHO

**Comment by tomakehurst** [comment]
@mdindoffer have you tried using the WireMock standalone JAR as your dependency?

This does shade Jetty so shouldn't collide.

**Comment by mdindoffer** [comment]
> @mdindoffer have you tried using the WireMock standalone JAR as your dependency?
> 
> This does shade Jetty so shouldn't collide.

OMG, you're right, I was using the plain flavour of the jar, `-standalone` solves the problem. 
Thanks.

**Comment by oleg-nenashev** [comment]
> I think it is kind of "as designed", because shading Jetty is not enough

So that part on my side was misleading, sorry for confusion
