### ISSUE TITLE
Error when trying to save stubs

### ISSUE THREAD

**Issue by vladp0v** [wiremock/wiremock#2340]
Running wiremock official image 2.35.0 in k8s pod, trying to save the stubs via API call: 
http://<domain>/__admin/mappings/save
Getting an error:
```
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1" />
	<title>Error 500 java.lang.IllegalArgumentException: Invalid UUID string: save</title>
</head>

<body>
	<h2>HTTP ERROR 500 java.lang.IllegalArgumentException: Invalid UUID string: save</h2>
	<table>
		<tr>
			<th>URI:</th>
			<td>/__admin/mappings/save</td>
		</tr>
		<tr>
			<th>STATUS:</th>
			<td>500</td>
		</tr>
		<tr>
			<th>MESSAGE:</th>
			<td>java.lang.IllegalArgumentException: Invalid UUID string: save</td>
		</tr>
		<tr>
			<th>SERVLET:</th>
			<td>com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-495ee280</td>
		</tr>
		<tr>
			<th>CAUSED BY:</th>
			<td>java.lang.IllegalArgumentException: Invalid UUID string: save</td>
		</tr>
	</table>
	<h3>Caused by:</h3>
	<pre>java.lang.IllegalArgumentException: Invalid UUID string: save
	at java.base/java.util.UUID.fromString(Unknown Source)
	at com.github.tomakehurst.wiremock.admin.tasks.GetStubMappingTask.execute(GetStubMappingTask.java:31)
	at com.github.tomakehurst.wiremock.http.AdminRequestHandler.handleRequest(AdminRequestHandler.java:82)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:75)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:142)
	at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
	at wiremock.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
	at wiremock.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
	at wiremock.org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:516)
	at wiremock.org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at wiremock.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at wiremock.org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at wiremock.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
</pre>

</body>

</html>
```
<img width="907" alt="Screenshot 2023-08-30 at 13 42 47" src="https://github.com/wiremock/wiremock/assets/127741943/686a6f2f-eebd-49ec-8abc-c37fd5cec032">

### Reproduction steps

1. Run the official image 2.35.0 in a k8s pod.
2. Create a stub.
3. Send an API call to save the stub

Doesn't reproduce when running the image locally

**Comment by tomakehurst** [comment]
Have you tried this with 3.0.0?

**Comment by vladp0v** [comment]
@tomakehurst No, I did not

**Comment by oleg-nenashev** [comment]
The same happens with "/__admin/mappings/reset" as reported in https://wiremock-community.slack.com/archives/C03NAEH5LVA/p1692795523226379?thread_ts=1692795523.226379&cid=C03NAEH5LVA for 2.35.0 . I will test it for 3.0.0. I would assume that there is some regression in Jetty's handler priority selection

**Comment by vladp0v** [comment]
@tomakehurst @oleg-nenashev 
Updated the image to 3.0.0-1
Same error
![Screenshot 2023-08-31 at 12 29 36](https://github.com/wiremock/wiremock/assets/127741943/58600f78-2ed6-4aa2-8545-c2c060ff9f45)

**Comment by oleg-nenashev** [comment]
@vladp0v I cannot reproduce it on vanilla 3.0.0 and a simple hello world stub. When a POST request is sent as documented, the  behavior is as expected. When a `GET` request is sent, it fails with the error you reported, but it is also an expected behavior

![image](https://github.com/wiremock/wiremock/assets/3000480/1848ee94-a4bb-48e4-a6c7-6facba3e45b9)

**Comment by vladp0v** [comment]
@oleg-nenashev it works locally in the pod
```
root@wiremock-0:/home/wiremock# curl -X POST http:/wiremock:8080/__admin/mappings/save
root@wiremock-0:/home/wiremock# ll
total 28
drwxr-xr-x 5 root root  4096 Aug 30 12:44 ./
drwxr-xr-x 1 root root    22 Aug 30 10:45 ../
drwxr-xr-x 2 root root  4096 Aug 30 12:44 __files/
drwx------ 2 root root 16384 Aug 30 12:44 lost+found/
drwxr-xr-x 2 root root  4096 Aug 31 10:58 mappings/
root@wiremock-0:/home/wiremock# cd mappings/
root@wiremock-0:/home/wiremock/mappings# ll
total 12
drwxr-xr-x 2 root root 4096 Aug 31 10:58 ./
drwxr-xr-x 5 root root 4096 Aug 30 12:44 ../
-rw-r--r-- 1 root root  349 Aug 31 10:58 post-messagingjson-551e7f3b-7fd7-46a5-a3ef-b560c7576b1c
root@wiremock-0:/home/wiremock/mappings#
```

**Comment by tomakehurst** [comment]
There isn't a route for `GET /__admin/mappings/save` only `POST`, so when you make a `GET` it hits the `/__admin/mappings/{id}` route instead, then can't parse `save` as a UUID.

We should add some better validation so that you get a 404 back rather than 500, but otherwise this is expected behaviour.

If you stick to using the `POST` for this request you should be fine.

**Comment by vladp0v** [comment]
@tomakehurst getting the same error for /reset.
All other endpoints IO tried work as expected

**Comment by tomakehurst** [comment]
Yeah, per my previous comment you need to `POST` otherwise it's going to try to retrieve by ID. Next version's error messages will make this clearer.

**Comment by vladp0v** [comment]
@tomakehurst 
I figured it out, was sending an http request to https, and POST was converted to GET.
Thank you, closing this

**Comment by oleg-nenashev** [comment]
Thanks for confirming it!
