### ISSUE TITLE
NoClassDefFoundError when using custom matcher with alpine image

### ISSUE THREAD

**Issue by jroy-998** [wiremock/wiremock#2439]
### Proposal

Http 500 error is returned when using a custom matcher with the latest alpine-main docker base image.

This is returned when the custom matcher is checked and will be returned for all matching calls. When the reference to the custom matcher is removed, all matching requests will function as expected.

Error stack trace:

```
java.lang.NoClassDefFoundError: com/github/tomakehurst/wiremock/stubbing/SubEvent
	at sample.SampleMatcher.match(SampleMatcher.java:16)
	at com.github.tomakehurst.wiremock.matching.RequestPattern.match(RequestPattern.java:221)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$3.apply(InMemoryStubMappings.java:231)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$3.apply(InMemoryStubMappings.java:229)
	at wiremock.com.google.common.collect.Iterators.find(Iterators.java:758)
	at wiremock.com.google.common.collect.Iterables.find(Iterables.java:693)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:76)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:229)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:59)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:75)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:142)
	at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:516)
	at wiremock.org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at wiremock.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at wiremock.org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.github.tomakehurst.wiremock.stubbing.SubEvent
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more
```

### Reproduction steps

Project has the following:

Gradle file:

```
plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

group 'sample'
archivesBaseName = 'wiremock-extensions'

sourceCompatibility = '11'
targetCompatibility = '11'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.wiremock:wiremock:3.1.0'
}

test {
    useJUnitPlatform()
}
```

Dockerfile:

```
FROM wiremock/wiremock:main-alpine

COPY ./build/libs/*.jar /var/wiremock/extensions/
COPY mappings.json /home/wiremock/mappings/

CMD [ \
  "--port=8102", \
  "--extensions=sample.SampleMatcher" \
]
```

Custom matchers:

```
package sample;

import com.github.tomakehurst.wiremock.extension.Parameters;
import com.github.tomakehurst.wiremock.http.Request;
import com.github.tomakehurst.wiremock.matching.MatchResult;
import com.github.tomakehurst.wiremock.matching.RequestMatcherExtension;

public class SampleMatcher extends RequestMatcherExtension {
    @Override
    public String getName() {
        return "sample";
    }

    @Override
    public MatchResult match(Request request, Parameters parameters) {
        return MatchResult.exactMatch();
    }
}
```

I thought this might be an issue with the packages/versions. But have checked and the project is using the same java (11) and Wiremock (3.1.0) as the Docker base image. I've also compared the custom matcher against the documentation and it is doing what is suggested.

Appreciate it may still be a mis-matching issue, but have checked everything I can think of and still seeing the issue so any suggestions would be greatly appreciated.

Thanks

### References

Checked previous issues for NoClassDefFoundError and can't find anything related. Have checked Wiremock versions and using the same java and Wiremock version between docker container and build package.

Checked message about issue with build tool so built a bare bones project and still seeing the issue.

Was working with a previous docker image.

**Comment by jroy-998** [comment]
Forgot to add the mappings file:

```
{
  "mappings": [
    {
      "request": {
        "urlPath": "/sample",
        "method": "GET"
      },
      "response": {
        "status": 200
      }
    },
    {
      "request": {
        "urlPath": "/custom-sample",
        "method": "GET",
        "customMatcher": {
          "name": "sample"
        }
      },
      "response": {
        "status": 418
      }
    }
  ]
}
```

**Comment by oleg-nenashev** [comment]
@jroy-998 Which versions of WireMock and the extensions do you sue? Seems to be a  WireMock 2/3 compatibility problem
