### ISSUE TITLE
Wiremock server sometimes responds with 500 when log limit is set

### ISSUE THREAD

**Issue by mykhaliev1** [wiremock/wiremock#2447]
### Proposal

Under high load wiremock server may respond with 500, when logs limit is set.
Reproducible with wiremock versions 3.0.2, 3.2.0
It happens ~0.01% of requests
<img width="1025" alt="image" src="https://github.com/wiremock/wiremock/assets/79195818/c3460f6f-5365-4550-9456-dc6b22b60c20">

### Reproduction steps

Steps to reproduce:
1) run standalone server from code: 
```
package org.example;
import static com.github.tomakehurst.wiremock.client.WireMock.*;

import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.core.WireMockConfiguration;


public class Main {

    public static void main(String[] args) {
        WireMockConfiguration wireMockConfiguration = WireMockConfiguration.options()
                                                                            .maxRequestJournalEntries(10)
                                                                           .port(8080);
        
        WireMockServer wireMockServer = new WireMockServer(wireMockConfiguration);

        wireMockServer.addStubMapping(get(urlEqualTo("/echo"))
            .willReturn(aResponse()
                .withStatus(200)
                .withBody("echo")).build());
        
        wireMockServer.start();
    }
}
```

2) Create and run a jmeter test, that calling /echo endpoint. I reproduced it with test, that is using 20 threads and 10000 iterations

Wiremock log:
```
[main] INFO org.eclipse.jetty.server.Server - jetty-11.0.16; built: 2023-08-25T19:43:30.438Z; git: bedff458c4dd1a716d59e17b8cb0d2042eeab291; jvm 17.0.7+8-LTS-224
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@346939bf{/__admin,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.handler.ContextHandler.ROOT - RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@741b3bc3{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started NetworkTrafficServerConnector@2c78324b{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:8080}
[main] INFO org.eclipse.jetty.server.Server - Started Server@295eaa7c{STARTING}[11.0.16,sto=1000] @678ms
[qtp837457281-21] WARN org.eclipse.jetty.server.HttpChannel - /echo
java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.concurrent.ConcurrentLinkedDeque$CLDSpliterator.forEachRemaining(ConcurrentLinkedDeque.java:1483)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
	at com.github.tomakehurst.wiremock.verification.AbstractRequestJournal.removeOldEntries(AbstractRequestJournal.java:125)
	at com.github.tomakehurst.wiremock.verification.AbstractRequestJournal.requestReceived(AbstractRequestJournal.java:70)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.beforeResponseSent(StubRequestHandler.java:88)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:96)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:157)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
[qtp837457281-29] WARN org.eclipse.jetty.server.HttpChannel - /echo
java.lang.NullPointerException
[qtp837457281-32] WARN org.eclipse.jetty.server.HttpChannel - /echo
java.lang.NullPointerException
[qtp837457281-26] WARN org.eclipse.jetty.server.HttpChannel - /echo
java.lang.NullPointerException
[qtp837457281-16] WARN org.eclipse.jetty.server.HttpChannel - /echo
java.lang.NullPointerException
[qtp837457281-30] WARN org.eclipse.jetty.server.HttpChannel - /echo
java.lang.NullPointerException
[qtp837457281-15] WARN org.eclipse.jetty.server.HttpChannel - /echo
java.lang.NullPointerException
```

**Comment by coder-hugo** [comment]
I'd say that the `InMemoryRequestJournalStore` is not thread-safe. I'd say that the code should be fine according to the documentation of the `ConcurrentLinkedDeque` and the `ConcurrentHashMap` but it looks like that sometimes there is a request missing in the `serveEvents` map for a `UUID` in the `deque`. Changing the `getAll()` as follows:
```
  public Stream<ServeEvent> getAll() {
    return deque.stream().map(serveEvents::get).filter(Objects::nonNull);
  }
```
should solve the `NullPointerException`. But it would be better to find the reason why there are sometimes `UUID`s in the `deque` that aren't present in the `serveEvents` map.
