### ISSUE TITLE
ListOrSingle cannot be cast to class java.lang.String 

### ISSUE THREAD

**Issue by Samir815** [wiremock/wiremock#2472]
### Proposal

I am using wiremock version 2.27.2 with java 17.

Getting below error (while executing test cases):

<500,<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /endpoint. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>wiremock.com.github.jknack.handlebars.HandlebarsException: inline@789b7364:7:49: java.lang.ClassCastException: class com.github.tomakehurst.wiremock.common.ListOrSingle cannot be cast to class java.lang.String (com.github.tomakehurst.wiremock.common.ListOrSingle is in unnamed module of loader &apos;app&apos;; java.lang.String is in module java.base of loader &apos;bootstrap&apos;)
    inline@789b7364:7:49
	at wiremock.com.github.jknack.handlebars.internal.Variable.value(Variable.java:181)
	at wiremock.com.github.jknack.handlebars.internal.Variable.merge(Variable.java:160)
	at wiremock.com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at wiremock.com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at wiremock.com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at wiremock.com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at wiremock.com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:100)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.HandlebarsOptimizedTemplate.apply(HandlebarsOptimizedTemplate.java:68)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.uncheckedApplyTemplate(ResponseTemplateTransformer.java:230)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.applyTemplatedResponseBody(ResponseTemplateTransformer.java:219)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.transform(ResponseTemplateTransformer.java:148)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.applyTransformations(InMemoryStubMappings.java:99)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:80)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:209)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:56)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:64)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:120)
	at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: class com.github.tomakehurst.wiremock.common.ListOrSingle cannot be cast to class java.lang.String (com.github.tomakehurst.wiremock.common.ListOrSingle is in unnamed module of loader &apos;app&apos;; java.lang.String is in module java.base of loader &apos;bootstrap&apos;)
	... 34 more
</pre>
<h3>Caused by:</h3><pre>java.lang.ClassCastException: class com.github.tomakehurst.wiremock.common.ListOrSingle cannot be cast to class java.lang.String (com.github.tomakehurst.wiremock.common.ListOrSingle is in unnamed module of loader &apos;app&apos;; java.lang.String is in module java.base of loader &apos;bootstrap&apos;)
	at wiremock.com.github.jknack.handlebars.internal.Variable.value(Variable.java:181)
	at wiremock.com.github.jknack.handlebars.internal.Variable.merge(Variable.java:160)
	at wiremock.com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at wiremock.com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at wiremock.com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at wiremock.com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at wiremock.com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:100)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.HandlebarsOptimizedTemplate.apply(HandlebarsOptimizedTemplate.java:68)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.uncheckedApplyTemplate(ResponseTemplateTransformer.java:230)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.applyTemplatedResponseBody(ResponseTemplateTransformer.java:219)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.transform(ResponseTemplateTransformer.java:148)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.applyTransformations(InMemoryStubMappings.java:99)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:80)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:209)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:56)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:64)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:120)
	at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre>
<hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
,[Content-Type:"text/html; charset=ISO-8859-1", Cache-Control:"must-revalidate,no-cache,no-store", Content-Length:"8066", Connection:"close", Server:"Jetty(9.2.z-SNAPSHOT)"]> 

### Reproduction steps

wiremock.com.github.jknack.handlebars.HandlebarsException: inline@789b7364:7:49: java.lang.ClassCastException: class com.github.tomakehurst.wiremock.common.ListOrSingle cannot be cast to class java.lang.String (com.github.tomakehurst.wiremock.common.ListOrSingle is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

**Comment by Samir815** [comment]
No further required.
