### ISSUE TITLE
Setting `max-request-journal-entries` causes NullPointerException with parallel requests

### ISSUE THREAD

**Issue by RasmusSoot** [wiremock/wiremock#2497]
### Proposal

`max-request-journal-entries` configuration causes NullPointerExceptions with parallel requests. 
We run Wiremock standalone with `max-request-journal-entries=100` and with functional tests that create 10 parallel requests. Sometimes Wiremock responds with HTTP 500 and java.lang.NullPointerException. 50:50 chance if error has a stacktrace included pointing to [store.getAllKeys().count()](https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/verification/AbstractRequestJournal.java#L125)
```
java.lang.NullPointerException
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
    at java.base/java.util.concurrent.ConcurrentLinkedDeque$CLDSpliterator.forEachRemaining(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.ReduceOps$5.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.ReduceOps$5.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.base/java.util.stream.ReferencePipeline.count(Unknown Source)
    at com.github.tomakehurst.wiremock.verification.AbstractRequestJournal.removeOldEntries(AbstractRequestJournal.java:125)
```

At other times without stacktrace it is just HTML page:
```
<body><h2>HTTP ERROR 500 java.lang.NullPointerException</h2>
<table>
    <tr>
        <th>URI:</th>
        <td>/test</td>
    </tr>
    <tr>
        <th>STATUS:</th>
        <td>500</td>
    </tr>
    <tr>
        <th>MESSAGE:</th>
        <td>java.lang.NullPointerException</td>
    </tr>
    <tr>
        <th>SERVLET:</th>
        <td>com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-7bf9b098</td>
    </tr>
    <tr>
        <th>CAUSED BY:</th>
        <td>java.lang.NullPointerException</td>
    </tr>
</table>
<h3>Caused by:</h3>
<pre>java.lang.NullPointerException</pre>
</body>
```

### Reproduction steps

Created a [gist](https://gist.github.com/RasmusSoot/51a73e5d38ec8d28bbe75cd26432dc02) with k6 performance test that always reproduces the issue on my machine - docker-compose.yml with simple mapping and k6 load test script. Run and it should print errors to console:
```shell
docker compose up -d wiremock
docker compose up k6
```
Increase --vus if this does not reproduce with 10 parallel requests.

**Comment by tomasbjerre** [comment]
Looks like a duplicate of #2447 and there was a PR fixing that in #2508

**Comment by RasmusSoot** [comment]
Yes, it is a duplicate. Reran test with current latest docker - wiremock/wiremock:3.5.2-1 and no more failures.
