### ISSUE TITLE
Wiremock 3.x has  CPU Throttling issue while running performance testing in docker containers

### ISSUE THREAD

**Issue by mehmetgul** [wiremock/wiremock#2541]
### Proposal

After upgrading wiremock 2.x to 3.x having CPU Throttling issue while running performance testing(locust in our case) in Docker containers.
Attached the 2 version comparison details (JFR files omitted incase having sensitive data but details shared in wiremock slack community)
[Issue Details.zip](https://github.com/wiremock/wiremock/files/13716759/Issue.Details.zip)

In our use case we have 4 WireMock  container used as User Profile with 5ms delay

**Each Container settings:**
```
resources:
  requests:
    cpu: 250m
    memory: 1024Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
```

**Expected Behavior:**
While running the performance test against 4 wiremock containers with 80K request per min with total 1mil request in 15 min, expecting that there will be no CPU throttling or Memory issue.

**Actual Behavior:** 
When running the performance test against 4 wiremock  container with 80K request per min, CPUT throttling starts after 3-4 min and it jumps almost 10-15 times of the CPU limits and causing containers to restart many times and crashing them.

### Reproduction steps

Issue can be reproduced by running wiremock in Docker containers with using locust performance testing with 20-80K request / per min ramp up in 10min.

### References

This issue discussed in wiremock slack community and here is the thread [Slack Thread ](https://wiremock-community.slack.com/archives/C03N1E6HFPY/p1701278515585739)

**Comment by mabre69uk** [comment]
is this still open? we can see CPU Throttling also in the last release 3.4.2...

**Comment by mehmetgul** [comment]
> is this still open? we can see CPU Throttling also in the last release 3.4.2...

Yes, Still the issue persist even after recent release.
You can use 2.33.2 version till it fixes.

**Comment by sebagomez** [comment]
FYI, I still see this issue in 3.9.1... and my stubs are not compatible with 2.33.2 :( 
When I start the 2.33.2 version I get the following exception
```
Exception in thread "main" com.github.tomakehurst.wiremock.standalone.MappingFileException: Error loading file /home/wiremock/./mappings/get_v5_my_stb.json:
Unrecognized field "urlPathTemplate" (class com.github.tomakehurst.wiremock.matching.RequestPattern), not marked as ignorable
        at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.loadMappingsInto(JsonFileMappingsSource.java:126)
        at com.github.tomakehurst.wiremock.core.WireMockApp.loadMappingsUsing(WireMockApp.java:221)
        at com.github.tomakehurst.wiremock.core.WireMockApp.loadDefaultMappings(WireMockApp.java:217)
        at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:112)
        at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:70)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:62)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:133)
```

**Comment by AM1988** [comment]
Hey!
I’m running into the same issue in my project too with `wiremock/wiremock:3.13.1-1`.

Just wanted to check — is there any update on this?
Did anyone find a workaround or a fix that worked for them?

Thanks in advance! 🙌

**Comment by pariaSadatHosseiny** [comment]
Hi,

We are also experiencing the same high CPU usage by wiremock for Performance tests on version: 3.13.2
Do you have any plan to fix it? :)

**Comment by tomakehurst** [comment]
@pariaSadatHosseiny have you tried version 4?

3.x is in security updates only mode and has been for quite a while. 4.x has moved on quite a bit.

If you still see the issue with 4.x please can you provide full reproduction information, as diagnosing performance bottlenecks is impossible without being able to recreate the conditions that produce it.

**Comment by pariaSadatHosseiny** [comment]
Hey @tomakehurst , unfortunately the issue occurs even with 4.0.0-beta.38-1 version.
I'll try to create a sample project that can reproduce the problem and let you know.
