### ISSUE TITLE
Matches helper in JSON configuration file containing regular expression with backslash+character does not match

### ISSUE THREAD

**Issue by jashburn8020** [wiremock/wiremock#2547]
### Proposal

It seems that the `matches` helper, which accepts regular expressions, does not match if the regular expression contains backslash+character, such as `\w`.

### Reproduction steps

The following does not match:

```json
{
  "metadata": {
    "description": "matches helper example"
  },
  "request": {
    "method": "GET",
    "urlPattern": "/matches/\\?string=[^&]+"
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    },
    "transformers": ["response-template"],
    "jsonBody": {
      "string matches": "{{#matches request.query.string 'lor\\w+'}}Matched{{/matches}}"
    }
  }
}
```

```console
$ curl localhost:8080/matches/?string=lorem
{"string matches":""}
```

I have tried doubling the backslashes, e.g., `'lor\\\\w+'`, but to no avail.

It does work if I don't use backslash+character in my regular expression:

```json
{
  "metadata": {
    "description": "matches helper example"
  },
  "request": {
    "method": "GET",
    "urlPattern": "/matches/\\?string=[^&]+"
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    },
    "transformers": ["response-template"],
    "jsonBody": {
      "string matches": "{{#matches request.query.string 'lor[a-z]+'}}Matched{{/matches}}"
    }
  }
}
```

```console
$ curl localhost:8080/matches/?string=lorem
{"string matches":"Matched"}
```

**Comment by G-Basak** [comment]
@jashburn8020 Thank you for the detailed reproduction step.

Can you try using a single backslash? That seems to work event though its not a valid JSON syntax anymore.
```json
{
  "metadata": {
    "description": "matches helper example"
  },
  "request": {
    "method": "GET",
    "urlPattern": "/matches/\\?string=[^&]+"
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    },
    "transformers": ["response-template"],
    "jsonBody": {
      "string matches": "{{#matches request.query.string 'lor\w+'}}Matched{{/matches}}"
    }
  }
}
```

**Comment by jashburn8020** [comment]
@G-Basak, thanks for your response. I have tried with a single backslash, but I can't get it to take effect.

If I have WireMock running before applying the single backslash, resetting the stub mappings (so that the change is read) throws an error:

```console
$ curl --request POST http://localhost:8080/__admin/mappings/reset
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 com.github.tomakehurst.wiremock.standalone.MappingFileException: Error loading file /path/to/mappings/helper-matches.json:
Unrecognized character escape &apos;w&apos; (code 119)
 at
 (... and so on...)
```

Restarting WireMock after applying the change doesn't work either - it stops WireMock from starting up:

```console
$ java -jar wiremock-standalone-3.3.1.jar 
Exception in thread "main" com.github.tomakehurst.wiremock.standalone.MappingFileException: Error loading file /path/to/mappings/helper-matches.json:
Unrecognized character escape 'w' (code 119)
 at [Source: (String)"{
  "metadata": {
    "description": "matches helper example"
  },
  "request": {
    "method": "GET",
    "urlPattern": "/matches/\\?string=[^&]+"
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    },
    "transformers": ["response-template"],
    "jsonBody": {
      "string matches": "{{#matches request.query.string 'lor\w+'}}Matched{{/matches}}"
    }
  }
}
"; line: 16, column: 64]
	at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.loadMappingsInto(JsonFileMappingsSource.java:123)
	at com.github.tomakehurst.wiremock.core.WireMockApp.loadMappingsUsing(WireMockApp.java:265)
	at com.github.tomakehurst.wiremock.core.WireMockApp.loadDefaultMappings(WireMockApp.java:259)
	at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:124)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:71)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:66)
	at wiremock.Run.main(Run.java:23)
```

**Comment by G-Basak** [comment]
Found the source of this problem.
https://github.com/wiremock/wiremock/blob/b3874f041baad7c7466a11dfabc5125f802799b4/src/main/java/com/github/tomakehurst/wiremock/http/Body.java#L58-L62

When constructing the response-body from JSON, it does not account for the escape sequences.
So, `\\` is stored and processes as literally `\\` and not converted into `\`. Same will happen with any other escape sequence such as `\"`, `\t`, `\n` etc.

**Comment by jashburn8020** [comment]
Thanks for the investigation, @G-Basak . :+1:

**Comment by G-Basak** [comment]
A quick and dirty PR to demonstrate the point : https://github.com/wiremock/wiremock/pull/2551
Will refine further to make it into a future release.

**Comment by G-Basak** [comment]
PR ready for review
https://github.com/wiremock/wiremock/pull/2551

**Comment by G-Basak** [comment]
The fix was released with [3.4.0](https://github.com/wiremock/wiremock/releases/tag/3.4.0)

**Comment by G-Basak** [comment]
The fix was reverted in [3.4.1](https://github.com/wiremock/wiremock/releases/tag/3.4.1) due to some issue found with the code.
