### ISSUE TITLE
WireMockHandlerDispatchingServlet.applyResponse needs fix when running Wiremock proxy on Servlet API 6

### ISSUE THREAD

**Issue by stefan-prange** [wiremock/wiremock#2556]
### Proposal

I'm integrating WireMock with Spring Boot 3.1.
The reason for wrapping WireMock inside Spring Boot is, that Spring Boot is our main backend technology and we already wrote a lot of Spring based code for test-data management.
Spring Boot 3.1 uses Tomcat 10 which in turn uses the Servlet API version 6.
Wiremock 3.3.1 is based on Jetty 11, which uses the Servlet API version 5. So WireMock 3.3.1 is prone to incompatibility issues when running it on Servlet API 6.

Problem:
I'm running WireMock's `WireMockHandlerDispatchingServlet` on Tomcat 10 (Servlet API 6). I defined a proxy mapping.
The response received from the remote site can't be processed by the method WireMockHandlerDispatchingServlet.applyResponse because that method uses the Servlet API method HttpServletResponse.setStatus(int, java.lang.String). That method was replaced in Servlet API 6 with the method HttpServletResponse.setStatus(int). 
Servlet API 6 doesn't support the response status reason phrase anymore.

The exception that is thrown:
```java
java.lang.NoSuchMethodError: 'void jakarta.servlet.http.HttpServletResponse.setStatus(int, java.lang.String)'
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.applyResponse(WireMockHandlerDispatchingServlet.java:260) ~[wiremock-3.3.1.jar:na]
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet$ServletHttpResponder.respondTo(WireMockHandlerDispatchingServlet.java:224) ~[wiremock-3.3.1.jar:na]
[...]
```

Expected Behavior:
I expected the proxy mapping to just work. That is, receiving the proxied site's response instead of WireMock's "Internal Server Error" caused by the exception mentioned above.

### Reproduction steps

I followed this wonderful guide for integrating WireMock with Spring Boot:
https://blog.jdriven.com/2023/02/building-a-stub-server-using-wiremock-and-spring-boot/

My java version is also 17, like in that guide, but my Spring Boot and WireMock versions differ:
Spring Boot: 3.1.4
WireMock: 3.3.1

I configured Spring Boot to let its Tomcat server listen on port 8216.

In the guide's `StubApplication` class, there is a method called `configureStubs`.
I changed its content to:
```java
    @EventListener(ApplicationReadyEvent.class)
    void configureStubs() {
        WireMock.configureFor("localhost", 8216);
        String PROXY_BASE_URL = "https://www.heise.de"; // /newsticker/
        stubFor(
            get(urlMatching("/heise/.*"))
                .willReturn(
                    aResponse()
                        .proxiedFrom(PROXY_BASE_URL)
                        .withProxyUrlPrefixToRemove("/heise")
                    )
            );
    }
```
The curl command for testing the proxy mapping is:
```
$ curl -is http://localhost:8216/heise/newsticker/
```

### References

Blog article used for integrating WireMock and Spring Boot:
https://blog.jdriven.com/2023/02/building-a-stub-server-using-wiremock-and-spring-boot/

WireMock's documentation page about proxy mappings:
https://wiremock.org/docs/proxying/

**Comment by stefan-prange** [comment]
I already managed to fix that problem by myself by changing the following code and compiling it into my own wiremock.jar. 
All of WireMock's unit tests passed while building that jar.

Class: `com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet`
Old code: Lines 248-262
```java
    if (response.getStatusMessage() == null) {
      httpServletResponse.setStatus(response.getStatus());
    } else {
      // The Jetty 11 does not implement HttpServletResponse::setStatus and always sets the
      // reason as `null`, the workaround using
      // org.eclipse.jetty.server.Response::setStatusWithReason
      // still works.
      if (httpServletResponse instanceof org.eclipse.jetty.server.Response) {
        final org.eclipse.jetty.server.Response jettyResponse =
            (org.eclipse.jetty.server.Response) httpServletResponse;
        jettyResponse.setStatusWithReason(response.getStatus(), response.getStatusMessage());
      } else {
        httpServletResponse.setStatus(response.getStatus(), response.getStatusMessage());
      }
    }
```

New code: Lines 248-275
```java
    if (response.getStatusMessage() == null) {
      httpServletResponse.setStatus(response.getStatus());
    } else {
      // The Jetty 11 does not implement HttpServletResponse::setStatus and always sets the
      // reason as `null`, the workaround using
      // org.eclipse.jetty.server.Response::setStatusWithReason
      // still works.
      if (httpServletResponse instanceof org.eclipse.jetty.server.Response) {
        final org.eclipse.jetty.server.Response jettyResponse =
            (org.eclipse.jetty.server.Response) httpServletResponse;
        jettyResponse.setStatusWithReason(response.getStatus(), response.getStatusMessage());
      } else {
        // The "reason" part of a response's status is no longer supported by Servlet
        // API 6.
        // So we need to find out which Servlet API we use and then use the appropriate
        // setStatus method.
        int servletApiMajorVersion = -1;
        ServletContext servletContext = httpServletRequest.getServletContext();
        if (servletContext != null) {
          servletApiMajorVersion = servletContext.getMajorVersion();
        }
        if (servletApiMajorVersion == 6) {
          httpServletResponse.setStatus(response.getStatus()); // ignore the statusMessage
        } else {
          httpServletResponse.setStatus(response.getStatus(), response.getStatusMessage());
        }
      }
    }
```

**Question:**
Would you mind integrating this fix into WireMock's next version?
Or do you consider my solution good enough to be part of a pull request? I'd be happy to file one.

**Comment by joostvdbroek93** [comment]
We have the same issue (Spring Boot 3.2.2, Wiremock 3.3.1, Java 17).

**Comment by leeturner** [comment]
Quick question, have you tried working with the release of WireMock that ships with Jetty 12?  This should remove the need for you to compile your own version into your spring boot app? 

The Jetty 12 version was originally released with version WireMock `3.5.0` and has been released with every version since up to the latest which is `3.6.0`

You can find the jetty 12 version here - https://mvnrepository.com/artifact/org.wiremock/wiremock-jetty12

Simple Spring Boot project using Spring Boot 3.x.x and jetty 12 is here - https://github.com/wiremock/wiremock-examples/tree/main/spring-boot/spring-boot-3/wiremock-jetty-12

**Comment by stefan-prange** [comment]
@leeturner 
I just tried my code with both dependencies, first with `org.wiremock:wiremock:3.8.0` and then again with `org.wiremock:wiremock-jetty12:3.8.0`.
I still doesn't work. I got the same exception in both attempts, see the stacktrace below.
The exception occurring in WireMockHandlerDispatchingServlet.applyResponse is different now.
```
java.lang.NullPointerException: Cannot invoke "com.github.tomakehurst.wiremock.jetty.JettyHttpUtils.setStatusWithReason(int, String, jakarta.servlet.http.HttpServletResponse)" because "this.utils" is null
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.applyResponse(WireMockHandlerDispatchingServlet.java:259) ~[wiremock-3.8.0.jar:3.8.0]
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet$ServletHttpResponder.respondTo(WireMockHandlerDispatchingServlet.java:232) ~[wiremock-3.8.0.jar:3.8.0]
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet$ServletHttpResponder.respondSync(WireMockHandlerDispatchingServlet.java:198) ~[wiremock-3.8.0.jar:3.8.0]
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet$ServletHttpResponder.respond(WireMockHandlerDispatchingServlet.java:192) ~[wiremock-3.8.0.jar:3.8.0]
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:102) ~[wiremock-3.8.0.jar:3.8.0]
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:165) ~[wiremock-3.8.0.jar:3.8.0]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.20.jar:6.0]
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:167) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:178) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) ~[tomcat-embed-core-10.1.20.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.6.jar:6.1.6]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.20.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-10.1.20.jar:10.1.20]
```

**Comment by ediccar** [comment]
I found a solution to the _"this.utils" is null_ issue.

Change the WireMockWebContextListener to a local one.
    @Bean
    WireMockWebContextListener WireMockWebContextListener() {
        return new MyWireMockWebContextListener();
    }
    
public class MyWireMockWebContextListener extends WireMockWebContextListener {

    @Override
    public void contextInitialized(ServletContextEvent sce) {

        super.contextInitialized(sce);
        ServletContext context = sce.getServletContext();
        context.setAttribute(JettyHttpUtils.class.getName(), new Jetty12HttpUtils());

    }

}
