### ISSUE TITLE
How to build standalone jar?

### ISSUE THREAD

**Issue by jkindwall** [wiremock/wiremock#26]
I'm interested in running WireMock in Standalone mode.  The documentation says to use this command:

$ java -jar wiremock-1.30-standalone.jar

However, I've thus far been unable to build this jar file.  I tried running "gradle build", and it got part way through the build process before failing with:

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':signArchives'.
  > Cannot perform signing task ':signArchives' because it has no configured signatory

In spite of this failure, it appears that the task did manage to build the following jars:

wiremock-1.31.jar
wiremock-1.31-javadoc.jar
wiremock-1.31-sources.jar

but not

wiremock-1.31-standalone.jar

I'm not seeing any other gradle tasks that look like they're used to build the standalone jar.  Am I missing something?

**Comment by oneeyedhobbit** [comment]
Sorry for posting in an old issue @tomakehurst, but I'm wondering if you have a basic build/development environment setup doc somewhere on github or wiremock.org?

I'm trying to integrate wiremock into an automated testing framework currently using cppunit (but hopefully moving to [catch](https://github.com/philsquared/Catch)).  I've come across a couple of issues that ended up being unrelated to wiremock, but it would be lovely to be able to build and debug wiremock via, say, intellij or eclipse.  Its been a while since I've used Java extensively (and even then it was android); do you have any sort of quick start guide you would consider sharing?

**Comment by tomakehurst** [comment]
Assume you mean building WireMock from source?

To test ``./gradlew test``
To build both JARs: ``./gradlew clean jar shadowJar``

**Comment by kratikagoyel** [comment]
I tried running gradle clean build jarAll

But Facing issues:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/kritikagoyal/repos/wiremock/build.gradle' line: 128

* What went wrong:
Execution failed for task ':jarAll'.
> Could not create an instance of type org.gradle.api.internal.artifacts.publish.DecoratingPublishArtifact_Decorated.
   > java.lang.UnsupportedOperationException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jarAll'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)

**Comment by kratikagoyel** [comment]
@tomakehurst kindly take a look
