### ISSUE TITLE
Enhancement: Add Option to Customize Jackson StreamReadConstraints in Wiremock Standalone

### ISSUE THREAD

**Issue by BenniG82** [wiremock/wiremock#2651]
### Proposal

Hello,

I'd like to suggest a feature for Wiremock Standalone that allows users to customize the Jackson StreamReadConstraints, specifically to adjust settings like maxStringLength. This setting limits the size of the JSON-Strings that could be parsed by Jackson.

Currently, for those of us using Wiremock in its embedded form, it's straightforward to modify these constraints with the following code snippet before starting Wiremock:

```java
StreamReadConstraints.overrideDefaultStreamReadConstraints(
    StreamReadConstraints.builder().maxStringLength(100_000_000).build()
);
```

However, this flexibility seems to be missing in the standalone version of Wiremock. While I understand that this issue stems more from Jackson than Wiremock itself, the ability to adjust these settings is crucial for our use case. We're dealing with some large mapping files, and being able to override the default maxStringLength setting would greatly help us.

Using Files larger than 20_000_000 bytes (Jacksons Defaut) leads to errors like this one:
```text
Caused by: com.github.tomakehurst.wiremock.standalone.MappingFileException: Error loading file big_mapping_file.json:
String value length (20053313) exceeds the maximum allowed (20000000, from `StreamReadConstraints.getMaxStringLength()`)
	at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.loadMappingsInto(JsonFileMappingsSource.java:126)
	at com.github.tomakehurst.wiremock.core.WireMockApp.loadMappingsUsing(WireMockApp.java:265)
	at com.github.tomakehurst.wiremock.core.WireMockApp.loadDefaultMappings(WireMockApp.java:259)
	at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:124)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:71)
```

**Comment by matheus-hatzlhoffer** [comment]
Do we have updates on this enhancement?

**Comment by andrey5608** [comment]
Hi @matheus-hatzlhoffer @BenniG82 
I've found a workaround. Please try it

Use the same code
```
StreamReadConstraints.overrideDefaultStreamReadConstraints(
    StreamReadConstraints.builder().maxStringLength(100_000_000).build()
);
```

but import it from another package.
`import wiremock.com.fasterxml.jackson.core.StreamReadConstraints`.

It's working in my project, hope it helps.
