### ISSUE TITLE
PatternSyntaxException in PathTemplate.SPECIAL_SYMBOL_REGEX on Android

### ISSUE THREAD

**Issue by arekolek** [wiremock/wiremock#2806]
### Proposal

In 3e33110cbcb596f01726e599ca6c4ad3941bf97c `PathTemplate.SPECIAL_SYMBOL_REGEX` was modified - escape character was removed from the closing brace `}`. It seems that it is fine on JVM but it crashes when I run it in an Android application.

### Reproduction steps

To reproduce you can run this sample app https://github.com/arekolek/WiremockCrash/blob/main/app/src/main/java/io/github/arekolek/wiremockcrash/MainActivity.kt

**Comment by arekolek** [comment]
But I guess trying to make it work is futile, after modifying it locally I encountered another issue, similar to https://github.com/jetty/jetty.project/issues/8912#issuecomment-1775755434, and after working around that, there's yet another issue:

```
                 Caused by: com.github.tomakehurst.wiremock.common.FatalStartupException: com.github.tomakehurst.wiremock.common.FatalStartupException: java.net.SocketException: Permission denied
                 	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:191)
                 	at io.github.arekolek.wiremockcrash.MainActivity.onCreate(MainActivity.kt:36)
                 	at android.app.Activity.performCreate(Activity.java:7327)
                 	at android.app.Activity.performCreate(Activity.java:7318)
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loop(Looper.java:214) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7050) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
                 Caused by: com.github.tomakehurst.wiremock.common.FatalStartupException: java.net.SocketException: Permission denied
                 	at com.github.tomakehurst.wiremock.jetty.JettyHttpServer.start(JettyHttpServer.java:144)
                 	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:189)
                 	at io.github.arekolek.wiremockcrash.MainActivity.onCreate(MainActivity.kt:36) 
                 	at android.app.Activity.performCreate(Activity.java:7327) 
                 	at android.app.Activity.performCreate(Activity.java:7318) 
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094) 
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loop(Looper.java:214) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7050) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
                 Caused by: java.net.SocketException: Permission denied
                 	at sun.nio.ch.Net.socket0(Native Method)
                 	at sun.nio.ch.Net.serverSocket(Net.java:424)
                 	at sun.nio.ch.ServerSocketChannelImpl.<init>(ServerSocketChannelImpl.java:88)
                 	at sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:56)
                 	at java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:108)
                 	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:334)
                 	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304)
                 	at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402)
                 	at org.eclipse.jetty.server.Server$$ExternalSyntheticLambda2.accept(D8$$SyntheticClass:0)
                 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
                 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:194)
                 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
                 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
                 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
                 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
                 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
                 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:133)
                 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:235)
                 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:419)
                 	at org.eclipse.jetty.server.Server.doStart(Server.java:398)
                 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
                 	at com.github.tomakehurst.wiremock.jetty.JettyHttpServer.start(JettyHttpServer.java:139)
                 	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:189) 
                 	at io.github.arekolek.wiremockcrash.MainActivity.onCreate(MainActivity.kt:36) 
                 	at android.app.Activity.performCreate(Activity.java:7327) 
                 	at android.app.Activity.performCreate(Activity.java:7318) 
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094) 
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loop(Looper.java:214) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7050) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```

So I'm guessing nobody is using wiremock on Android anymore?

**Comment by pbelov** [comment]
same issue with 3.9.1 and lower

**Comment by rolgalan** [comment]
> So I'm guessing nobody is using wiremock on Android anymore?

I was using it, but still in version `2.26.3` which looks like is the only Wiremock version that works nowadays. We had it fixed for a long time and never tried to update until now.

I managed to make it work the version `2.35.2`, the last one from the 2.x branch (released last February, so nicer than a 4 years old version). **This version will work if your minSdkVersion is 26 or above** (due to a jetty requirement). Unfortunately we are still in minSdk 24, so I can't go with this bump. So if your app is above sdk 26 you can give it a try to that version.

The funny thing is that if you proguard the build it works even for api<26, I guess that the specific line with the incompatible code is stripped out away due not being even required by Wiremock on Android. 🤷 (but this is also not suitable for us due to the extended build time that engineers would face when running ui tests locally).

Regarding the 3.x versions: As you mentioned, even if this PatternSyntaxException was solved, **all the 3.x versions are totally incompatible with Android** due to the [Jetty issue](https://github.com/jetty/jetty.project/issues/8912) with the `java.util.ServiceLoader`. Reading the answers from the Jetty maintainers, it doesn't look like this is going to be resolved anytime soon. Since this is a hard dependency for Wiremock I don't think we are going to see any Android compatible version in the medium term. So, answering to the quoted question: most likely no one started to use it in the last 4 years that it has been broken for Android, and whoever used it in the past will be in the process of migrating due to the lack of support. Time to look for alternatives.

**Comment by emartynov** [comment]
> But I guess trying to make it work is futile, after modifying it locally I encountered another issue, similar to [jetty/jetty.project#8912 (comment)](https://github.com/jetty/jetty.project/issues/8912#issuecomment-1775755434), and after working around that, there's yet another issue:
> 
> ```
>                  Caused by: com.github.tomakehurst.wiremock.common.FatalStartupException: com.github.tomakehurst.wiremock.common.FatalStartupException: java.net.SocketException: Permission denied
>                  	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:191)
>                  	at io.github.arekolek.wiremockcrash.MainActivity.onCreate(MainActivity.kt:36)
>                  	at android.app.Activity.performCreate(Activity.java:7327)
>                  	at android.app.Activity.performCreate(Activity.java:7318)
>                  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
>                  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
>                  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
>                  	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
>                  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
>                  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
>                  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
>                  	at android.os.Handler.dispatchMessage(Handler.java:106) 
>                  	at android.os.Looper.loop(Looper.java:214) 
>                  	at android.app.ActivityThread.main(ActivityThread.java:7050) 
>                  	at java.lang.reflect.Method.invoke(Native Method) 
>                  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
>                  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
>                  Caused by: com.github.tomakehurst.wiremock.common.FatalStartupException: java.net.SocketException: Permission denied
>                  	at com.github.tomakehurst.wiremock.jetty.JettyHttpServer.start(JettyHttpServer.java:144)
>                  	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:189)
>                  	at io.github.arekolek.wiremockcrash.MainActivity.onCreate(MainActivity.kt:36) 
>                  	at android.app.Activity.performCreate(Activity.java:7327) 
>                  	at android.app.Activity.performCreate(Activity.java:7318) 
>                  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
>                  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094) 
>                  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
>                  	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
>                  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
>                  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
>                  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
>                  	at android.os.Handler.dispatchMessage(Handler.java:106) 
>                  	at android.os.Looper.loop(Looper.java:214) 
>                  	at android.app.ActivityThread.main(ActivityThread.java:7050) 
>                  	at java.lang.reflect.Method.invoke(Native Method) 
>                  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
>                  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
>                  Caused by: java.net.SocketException: Permission denied
>                  	at sun.nio.ch.Net.socket0(Native Method)
>                  	at sun.nio.ch.Net.serverSocket(Net.java:424)
>                  	at sun.nio.ch.ServerSocketChannelImpl.<init>(ServerSocketChannelImpl.java:88)
>                  	at sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:56)
>                  	at java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:108)
>                  	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:334)
>                  	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304)
>                  	at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402)
>                  	at org.eclipse.jetty.server.Server$$ExternalSyntheticLambda2.accept(D8$$SyntheticClass:0)
>                  	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
>                  	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:194)
>                  	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
>                  	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
>                  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
>                  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
>                  	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
>                  	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:133)
>                  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:235)
>                  	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:419)
>                  	at org.eclipse.jetty.server.Server.doStart(Server.java:398)
>                  	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
>                  	at com.github.tomakehurst.wiremock.jetty.JettyHttpServer.start(JettyHttpServer.java:139)
>                  	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:189) 
>                  	at io.github.arekolek.wiremockcrash.MainActivity.onCreate(MainActivity.kt:36) 
>                  	at android.app.Activity.performCreate(Activity.java:7327) 
>                  	at android.app.Activity.performCreate(Activity.java:7318) 
>                  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
>                  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094) 
>                  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
>                  	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
>                  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
>                  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
>                  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
>                  	at android.os.Handler.dispatchMessage(Handler.java:106) 
>                  	at android.os.Looper.loop(Looper.java:214) 
>                  	at android.app.ActivityThread.main(ActivityThread.java:7050) 
>                  	at java.lang.reflect.Method.invoke(Native Method) 
>                  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
>                  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
> ```
> 
> So I'm guessing nobody is using wiremock on Android anymore?

@arekolek how did you modify it locally? Did you try to make own wiremock binary with changes?

**Comment by arekolek** [comment]
> how did you modify it locally?
@emartynov using https://docs.gradle.org/current/userguide/composite_builds.html#included_build_declaring_substitutions you can see here: https://github.com/arekolek/WiremockCrash/blob/workaround/settings.gradle.kts#L26 - `../wiremock` points to my local clone of `wiremock` repo - then I can edit it in Android Studio as if it was yet another module in my project

**Comment by arekolek** [comment]
> I managed to make it work the version 2.35.2

@rolgalan I too updated to version 2.35.0 after all (I missed there was a 2.35.2 I guess, not sure if I tried it)

Thanks for sharing all the interesting things you found

**Comment by emartynov** [comment]
> > how did you modify it locally?
> 
> @emartynov using https://docs.gradle.org/current/userguide/composite_builds.html#included_build_declaring_substitutions
> 
> I pushed it to Github, so you can see here: https://github.com/arekolek/WiremockCrash/blob/workaround/settings.gradle.kts#L26 - `../wiremock` points to my local clone of `wiremock` repo - then I can edit it in Android Studio as if it was yet another module in my project

Thanks! I don't think we are going to maintain version of the wiremock source with one change.

**Comment by arekolek** [comment]
Yeah, I wouldn't do it either.

I was just trying to see if there's potential to fix it with a simple PR.
