### ISSUE TITLE
wiremock fails when jackson-databind 2.18.0 is on classpath

### ISSUE THREAD

**Issue by m-schutte-ohra-nl** [wiremock/wiremock#2868]
### Proposal

This is not a classpath issue as stated above, but instead an incompatibility with the latest version of jackson-databind.

When wiremock is used in a setup where com.fasterxml.jackson.core:jackson-databind:2.18.0 is on the classpath it can fail with the below stacktrace. 

> Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Conflicting property-based creators: already had implicit creator [constructor for `com.github.tomakehurst.wiremock.matching.EqualToXmlPattern` (1 arg), annotations: [null], encountered another: [constructor for `com.github.tomakehurst.wiremock.matching.EqualToXmlPattern` (3 args), annotations: [null] (through reference chain: java.util.ImmutableCollections$List12[0])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
        at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1328)
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1475)
        at com.fasterxml.jackson.databind.SerializerProvider.findContentValueSerializer(SerializerProvider.java:811)
        at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSecondarySerializer(PropertySerializerMap.java:90)
        at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase._findAndAddDynamic(AsArraySerializerBase.java:314)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:115)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1583)
        at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1285)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1140)
        at com.github.tomakehurst.wiremock.common.Json.write(Json.java:104)
        at com.github.tomakehurst.wiremock.common.Json.write(Json.java:90)
        at EqualToXmlPatternTest.main(EqualToXmlPatternTest.java:12)

### Reproduction steps

- Expand the attachment wiremock.zip and open a cmd prompt in the directory containing pom.xml
- To trigger the error run:
-- (linux)  mvn clean compile exec:exec -Djackson=2.18.0 -Dexec.executable=java
-- (windows)  mvn clean compile exec:exec -Djackson=2.18.0 -Dexec.executable=java.exe
- To see normal execution run:
-- (linux)  mvn clean compile exec:exec -Djackson=2.17.2 -Dexec.executable=java
-- (windows)  mvn clean compile exec:exec -Djackson=2.17.2 -Dexec.executable=java.exe
[wiremock.zip](https://github.com/user-attachments/files/17375865/wiremock.zip)

**Comment by dev-ducu** [comment]
Is there a plan to fix this?

**Comment by m-schutte-ohra-nl** [comment]
This has been fixed in wiremock 3.10.0, closing issue
