### ISSUE TITLE
Dynamic certificate generation does not work with Java 23 (and perhaps earlier?)

### ISSUE THREAD

**Issue by Mahoney** [wiremock/wiremock#2881]
### Summary

If you enable browser proxying on Java 23 you get the following error:
```
2024-10-24 18:00:30.216 Dynamic certificate generation is not supported because certificates cannot be generated; perhaps the sun internal classes are not available?
All sites will be served using the normal WireMock HTTPS certificate.
com.github.tomakehurst.wiremock.http.ssl.CertificateGenerationUnsupportedException: Your runtime does not support generating certificates at runtime
	at com.github.tomakehurst.wiremock.http.ssl.CertificateAuthority.generateCertificate(CertificateAuthority.java:148)
	at com.github.tomakehurst.wiremock.http.ssl.DynamicKeyStore.generateCertificate(DynamicKeyStore.java:64)
	at com.github.tomakehurst.wiremock.http.ssl.DynamicKeyStore.generateCertificateIfNecessary(DynamicKeyStore.java:53)
	at com.github.tomakehurst.wiremock.http.ssl.CertificateGeneratingX509ExtendedKeyManager.chooseServerAlias(CertificateGeneratingX509ExtendedKeyManager.java:176)
	at com.github.tomakehurst.wiremock.http.ssl.CertificateGeneratingX509ExtendedKeyManager.chooseServerAlias(CertificateGeneratingX509ExtendedKeyManager.java:142)
	at com.github.tomakehurst.wiremock.http.ssl.CertificateGeneratingX509ExtendedKeyManager.tryToChooseServerAlias(CertificateGeneratingX509ExtendedKeyManager.java:125)
	at com.github.tomakehurst.wiremock.http.ssl.CertificateGeneratingX509ExtendedKeyManager.chooseEngineServerAlias(CertificateGeneratingX509ExtendedKeyManager.java:92)
	at java.base/sun.security.ssl.X509Authentication.createServerPossession(X509Authentication.java:289)
	at java.base/sun.security.ssl.X509Authentication.createPossession(X509Authentication.java:195)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.choosePossession(CertificateMessage.java:1062)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.onProduceCertificate(CertificateMessage.java:973)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.produce(CertificateMessage.java:964)
	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:437)
	at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.goServerHello(ClientHello.java:1243)
	at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.consume(ClientHello.java:1179)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:837)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:798)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1274)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1260)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1205)
	at wiremock.org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:657)
	at wiremock.org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:373)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at wiremock.org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
	at wiremock.org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
	at wiremock.org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at wiremock.org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:193)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.NoSuchMethodError: 'void sun.security.x509.CertificateExtensions.set(java.lang.String, java.lang.Object)'
	at com.github.tomakehurst.wiremock.http.ssl.CertificateAuthority.subjectAlternativeName(CertificateAuthority.java:204)
	at com.github.tomakehurst.wiremock.http.ssl.CertificateAuthority.generateCertificate(CertificateAuthority.java:132)
	... 40 more
```

It looks like there have been several breaking changes - `X509CertInfo.set(String, String)`, `X509CertImpl.sign(PrivateKey, String)` and `CertificateExtensions.set(String, String)` are all no longer present.

Should we seek to support ongoing?

Switch to a library that can do the generation?

**Comment by kdebski85** [comment]
Looking at https://github.com/openjdk/jdk/commit/671f84bd8625ea7e06fa8272ae629309df06e9ca#diff-0b9f279d1a1537d66ce5adf4e2abcff9a15d4905f500539a6cf52e9f6710aef7R178
the method `set(java.lang.String, java.lang.Object)` was removed and `setExtension(String name, Extension ext)` was added.

**Comment by SingingBush** [comment]
I'm using wiremock 3.13.1 and just encountered this issue. Seems the code is still using the old methods. eg: https://github.com/wiremock/wiremock/blob/1210d3898b957990c46101b790908e87fcd1c9ef/wiremock-common/src/main/java/com/github/tomakehurst/wiremock/http/ssl/CertificateAuthority.java#L94-L99

**Comment by orcunbalcilar** [comment]
any update on this issue?

**Comment by AnttiSuolahti** [comment]
For me this is also occurring with JDK 17 and wiremock-standalone.
As a workaround I was able to make it work by adding  exports to surefire.
`
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-surefire-plugin</artifactId>
<version>3.5.2</version>
<configuration>
<testFailureIgnore>true</testFailureIgnore>
<argLine>
--add-exports java.base/sun.security.provider=ALL-UNNAMED
--add-exports java.base/sun.security.pkcs=ALL-UNNAMED
--add-exports java.base/sun.security.util=ALL-UNNAMED
--add-exports java.base/sun.security.x509=ALL-UNNAMED
</argLine>
</configuration>
</plugin>
`

**Comment by SingingBush** [comment]
> For me this is also occurring with JDK 17 and wiremock-standalone. As a workaround I was able to make it work by adding exports to surefire....

That's something else, this isn't about JPMS, it's about a change in the JDK where `set(java.lang.String, java.lang.Object)` has been replaced by `setExtension(String name, Extension ext)`.

JDK 17 has the older method. See kdebski85's comment.
