### ISSUE TITLE
FormatXmlHelper constructor may throw IllegalArgumentException depending on the TransformerFactory impl

### ISSUE THREAD

**Issue by jamesnetherton** [wiremock/wiremock#2911]
### Proposal

Something observed in my project when attempting to upgrade WireMock to 3.10. Depending on the `TransformerFactory` implementation in use, the constructor logic in `FormatXmlHelper` that attempts to set attributes on the factory may throw an `IllegalArgumentException`.

For example, I have one set of tests where `xalan` is on the classpath:

```
Caused by: java.lang.IllegalArgumentException: TransformerFactory does not recognise attribute 'http://javax.xml.XMLConstants/property/accessExternalDTD'.
	at org.apache.xalan.xsltc.trax.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:373)
	at org.apache.camel.quarkus.support.xalan.XalanTransformerFactory.setAttribute(XalanTransformerFactory.java:101)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.FormatXmlHelper.(FormatXmlHelper.java:69)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers$30.(WireMockHelpers.java:284)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers.(WireMockHelpers.java:283)
```

In some other tests, Saxon-HE is on the classpath:

```
Caused by: java.lang.IllegalArgumentException: Unrecognized configuration feature: indent-number
	at net.sf.saxon.Configuration.setConfigurationProperty(Configuration.java:4378)
	at net.sf.saxon.jaxp.SaxonTransformerFactory.setAttribute(SaxonTransformerFactory.java:340)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.FormatXmlHelper.(FormatXmlHelper.java:68)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers$30.(WireMockHelpers.java:284)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers.(WireMockHelpers.java:283)
```

Maybe `FormatXmlHelper` should gracefully handle this or is there any way to disable specific helpers?

### Reproduction steps

Create an empty application with the following dependencies:

```xml
<dependency>
  <groupId>org.wiremock</groupId>
  <artifactId>wiremock-standalone</artifactId>
  <version>3.10.0</version>
</dependency>
<dependency>
  <groupId>net.sf.saxon</groupId>
  <artifactId>Saxon-HE</artifactId>
  <version>12.5</version>
</dependency>
```

Then try to instantiate a `WireMockServer`:

```java
WireMockServer server = new WireMockServer();
```

It should result in:

```
Caused by: java.lang.IllegalArgumentException: Unrecognized configuration feature: indent-number
	at net.sf.saxon.Configuration.setConfigurationProperty(Configuration.java:4378)
	at net.sf.saxon.jaxp.SaxonTransformerFactory.setAttribute(SaxonTransformerFactory.java:340)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.FormatXmlHelper.<init>(FormatXmlHelper.java:68)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers$30.<init>(WireMockHelpers.java:284)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers.<clinit>(WireMockHelpers.java:283)
```

**Comment by turing85** [comment]
I can confirm the the behaviour observed with `xalan`, we use version `2.7.2`. 

Note that:
- the properties `XMLConstants.ACCESS_EXTERNAL_DTD` and  `XMLConstants.ACCESS_EXTERNAL_STYLESHEET` are requred by JAXP 1.5 implementation
- `xalan` is "only" compatible with JAXP 1.3 (see [here (`xalan.apache.org`)](https://xalan.apache.org/xalan-j/readme.html#notes_270), and
- an upgrade to `xalan` version `2.7.2` may not be possible for camel-quarkus users, see https://github.com/apache/camel-quarkus/issues/4065#issuecomment-2198842434

It would be really nice to have a fix that continues to support `xalan`.

**Comment by ejbartelds** [comment]
I can confirm the same situation as well, this time with `xalan` version `2.7.3`.  

Unfortunately, for reasons that are beyond our control (and which won't make you happy anyway if I'd explain them...), we cannot step away from this particular `xalan` version.

It would be really nice indeed to have a fix.

**Comment by JanMosigItemis** [comment]
Temurin 21 here:

```java
Caused by: java.lang.IllegalArgumentException: Unrecognized configuration feature: indent-number
[INFO]  at net.sf.saxon.Configuration.setConfigurationProperty(Configuration.java:4373)
[INFO]  at net.sf.saxon.jaxp.SaxonTransformerFactory.setAttribute(SaxonTransformerFactory.java:340)
[INFO]  at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.FormatXmlHelper.<init>(FormatXmlHelper.java:6
8)
[INFO]  at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers$30.<init>(WireMockHelpers.jav
a:284)
[INFO]  at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers.<clinit>(WireMockHelpers.java
```

**Comment by ThomHurks** [comment]
We have the same problem. In a project that uses `docx4j`, if we update WireMock to 3.10.0 we get the following stacktrace when initializing the WireMockServer:
```
java.lang.ExceptionInInitializerError
	at com.github.tomakehurst.wiremock.extension.responsetemplating.TemplateEngine.addHelpers(TemplateEngine.java:105)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.TemplateEngine.<init>(TemplateEngine.java:77)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.TemplateEngine.defaultTemplateEngine(TemplateEngine.java:56)
	at com.github.tomakehurst.wiremock.common.filemaker.FilenameMaker.<init>(FilenameMaker.java:44)
	at com.github.tomakehurst.wiremock.common.filemaker.FilenameMaker.<init>(FilenameMaker.java:40)
	at java.base/java.util.Objects.requireNonNullElseGet(Objects.java:314)
	at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.<init>(JsonFileMappingsSource.java:44)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.getMappingsSource(WireMockConfiguration.java:157)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.mappingsLoader(WireMockConfiguration.java:684)
	at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:96)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:68)
	at com.myorg.app.fooprocessor.extentions.WireMockExtension.beforeAll(WireMockExtension.kt:28)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	Suppressed: kotlin.UninitializedPropertyAccessException: lateinit property mockServer has not been initialized
		at com.myorg.app.fooprocessor.extentions.WireMockExtension.afterAll(WireMockExtension.kt:19)
		... 1 more
Caused by: java.lang.IllegalArgumentException: Not supported: indent-number
	at org.docx4j.org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:571)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.FormatXmlHelper.<init>(FormatXmlHelper.java:68)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers$30.<init>(WireMockHelpers.java:284)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers.<clinit>(WireMockHelpers.java:283)
	... 13 more
```
Looking at the dependency tree it seems `docx4j` depends on `xalan`, so I don't think we can easily work around this issue.
