### ISSUE TITLE
NullPointerException when running tests from multiple classes that extend a base class with WireMockClassRule

### ISSUE THREAD

**Issue by ianmachuca** [wiremock/wiremock#2912]
### Proposal

I am attempting to convert an application to Spring Boot 3 and running into an error using WireMockClassRule. I have a set of tests that all extend a base class, where the base class instantiates a WireMockClassRule. When any single test or test class is run individually, the test will succeed. When I run multiple test classes in the same run, the first class to run will have all of its tests pass but then every other test (that calls stubFor) from a different class will result in the following error:
```
java.lang.NullPointerException: Cannot invoke "com.github.tomakehurst.wiremock.http.RequestHandler.handle(com.github.tomakehurst.wiremock.http.Request, com.github.tomakehurst.wiremock.http.HttpResponder, com.github.tomakehurst.wiremock.stubbing.ServeEvent)" because "this.requestHandler" is null
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:165)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:317)
	at org.eclipse.jetty.ee10.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:270)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:819)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	at org.eclipse.jetty.server.Handler$Sequence.handle(Handler.java:805)
	at org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Expected status 2xx for http://localhost:10099/__admin/mappings but was 500
com.github.tomakehurst.wiremock.client.VerificationException: Expected status 2xx for http://localhost:8181/__admin/mappings but was 500
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.verifyResponseStatus(HttpAdminClient.java:531)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.safelyExecuteRequest(HttpAdminClient.java:549)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.executeRequest(HttpAdminClient.java:511)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.executeRequest(HttpAdminClient.java:486)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:151)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:471)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:466)
	at com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:130)
	at com.github.tomakehurst.wiremock.client.WireMock.stubFor(WireMock.java:134)
```

### Reproduction steps

Start with an new Spring Boot java 21 project.

Gradle File:
```
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.0'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation "junit:junit:4.13"
    testImplementation "org.wiremock:wiremock-jetty12:3.10.0"
}
```

TestBase File:
```
@SpringBootTest
public abstract class WmTestBase {

    @ClassRule
    public static WireMockClassRule wireMockRule = new WireMockClassRule(10099);
    @Rule
    public WireMockClassRule instanceRule = wireMockRule;

    protected void stub(UrlPattern url, int status, String response) {
        var updatedResponse = aResponse().withStatus(status).withBody(response);
        stubFor(get(url).willReturn(updatedResponse));
    }
}
```
Then define two or more test classes similar to the following the extend the TestBase and call stubFor:
```
public class ExampleTestA extends WmTestBase {
    @Test
    public void test_A1() {
        stub(urlMatching("/api/v1/get1"), 200, "TestResponse-G1");
    }
    @Test
    public void test_A2() {
        stub(urlMatching("/api/v1/get2"), 200, "TestResponse-G2");
    }
}
```

When all tests are run, you will see the first class succeeds and all other tests fail.

**Comment by ianmachuca** [comment]
I have created a repro project: https://github.com/ianmachuca/WireMockClassRule-Bug

**Comment by tomakehurst** [comment]
Thanks for sharing this. I see the issue now but it seems it's going to be a pain to fix as it's due to a change in the way Jetty 12 (vs. 11) handles the servlet context.

I suggest using the instance rule instead, at least for now:

```java
@Rule
public WireMockRule wireMockRule = new WireMockRule(8181);
```
