### ISSUE TITLE
Vanilla Spring Boot app using Wiremock throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by snicoll** [wiremock/wiremock#2922]
### Proposal

Recent Spring Boot versions have been migrated to Jetty 12 that is not backward compatible with Jetty 11. If you use wiremock in such an environment where Jetty 12 is managed, an empty `@WiremockTest` fails as follows:

```

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.github.tomakehurst.wiremock.http.HttpServerFactoryLoader.pickMostAppropriateFrom(HttpServerFactoryLoader.java:77)
	at com.github.tomakehurst.wiremock.http.HttpServerFactoryLoader.load(HttpServerFactoryLoader.java:57)
	at com.github.tomakehurst.wiremock.WireMockServer.getHttpServerFactory(WireMockServer.java:89)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:72)
	at com.github.tomakehurst.wiremock.junit5.WireMockExtension.startServerIfRequired(WireMockExtension.java:215)
	at com.github.tomakehurst.wiremock.junit5.WireMockExtension.beforeAll(WireMockExtension.java:282)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

This is due to `HttpServerFactoryLoader#pickMostAppropriateFrom` expecting the list of `HttpServerFactory` is non-empty where, in fact, it is.

### Reproduction steps

```
git clone https://github.com/snicoll-scratches/wiremock-demo
cd wiremock-demo
./gradlew test
```

**Comment by sverdiyev** [comment]
This is not a bug. 

Change 
testImplementation "org.wiremock:wiremock:3.10.0"
to 
testImplementation "org.wiremock:wiremock-standalone:3.10.0"

and that will solve your issue.

**Comment by sverdiyev** [comment]
In the meantime, you can use wiremock-standalone. 

testImplementation "org.wiremock:wiremock-standalone:3.10.0"

**Comment by leeturner** [comment]
Thank you for reporting the issue and providing a demo of the problem.  A demo app always helps us figure out what is happening quicker.  The issue is caused by a mix of dependencies within your application.  You are using the `3.x.x` release of Spring Boot which brings in the Jetty 12 dependency.  As you mentioned, at the moment, WireMock core uses Jetty 11.  This is why you are seeing the error.  We released a [Jetty 12 version of WireMock a](https://mvnrepository.com/artifact/org.wiremock/wiremock-jetty12) little while ago to better support frameworks that have moved to Jetty 12.  Using the updated dependency should solve your problem.

Update this dependency:

```
testImplementation "org.wiremock:wiremock:3.10.0"
```

To this dependency:

```
testImplementation "org.wiremock:wiremock-jetty12:3.10.0"
```

I have tested this on your demo app and it works fine.

The main issue is that the error message is not very descriptive regarding what the actual problem is.  We have recently had a community member submit a fix for this which will go out in the next release of WireMock - https://github.com/wiremock/wiremock/pull/2920

I'll close this issue for now but if you are having any further issues please join us on the community slack - https://slack.wiremock.org/
