### ISSUE TITLE
SSL exception when trying to proxy https

### ISSUE THREAD

**Issue by SvenSchindler** [wiremock/wiremock#68]
Hi,

we're trying to use wiremock as an https proxy between our application and a remote server (we would like to filter a subset of requests). We set the https port in the wiremock configuration. However, we are getting the following error when our application tries to establish an https connection:

javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
    at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:671) ~[na:1.7.0_45]
    at sun.security.ssl.InputRecord.read(InputRecord.java:504) ~[na:1.7.0_45]
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927) ~[na:1.7.0_45]
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312) ~[na:1.7.0_45]
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339) ~[na:1.7.0_45]
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323) ~[na:1.7.0_45]
    at wiremock.org.mortbay.jetty.security.SslSocketConnector$SslConnection.run(SslSocketConnector.java:708) ~[wiremock-1.36-standalone.jar:na]
    at com.github.tomakehurst.wiremock.jetty.DelayableSslSocketConnector$1.run(DelayableSslSocketConnector.java:54) [wiremock-1.36-standalone.jar:na]
    at wiremock.org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [wiremock-1.36-standalone.jar:na] 

Did we miss anything or is this a known issue? Thanks for your help.

**Comment by fengverson** [comment]
Hi tomakehurst,

I am planning to migrate betamax to wiremock for record and replay purpose. Betamax basically plays as middle man between client and service however, it doesn't have support for https proxying. I realized wiremock didn't solve this problem directly as well. Instead wiremock create separate conversation between client -> wiremock and wiremock -> service.  so my question is that when you create wiremock, the reason you design this way is to avoid https proxying issue?  I am not familiar with HTTPS. Is this the only way to solve https record and replay issue? 

Thanks,

**Comment by tomakehurst** [comment]
Unfortunately, the decrypt + re-encrypt approach is the only viable option for HTTPS, the reason being that WireMock needs to see the contents of the request in order to decide what to do with it.

Some proxy servers are able to act as pass-through HTTPS proxies, but they do this via the CONNECT HTTP method, which essentially turns them into TCP proxies (which means they don't need to see the request's contents, just the target IP address).
